// Hinglish base data (numbers, kua, personal year/month, labels).
import type { ColorKey, DirKey, DayPartKey, NumData, RelKey } from "../types";

export const ui: Record<string, string> = {
  printedOn: "Printed on",
  languageSwitchNote: "PDF export karne se pehle bhasha jitni baar chahein badal sakte hain.",
  kua5Note: "Kua 5 apni koi disha nahi rakhta — Disha, Vastu aur Urja ke liye iska behaves-as Kua lagu hota hai.",
  thanksTitle: "Dhanyavaad",
  thanksHello: "Aadarniya",
  thanksBody: "aapne NAMAANK par bharosa kiya — iske liye dil se aabhaar. Yeh report aapke naam, janm tarikh, samay aur sthaan ko ginti ke niyamon se jodkar poori mehnat se taiyaar ki gayi hai.",
  thanksBody2: "Ank sirf raasta dikhate hain, chalna aapko hai. Yahan diye gaye upay chhote hain par niyam se karne par asar bada hota hai — 40 din lagataar karke apne andar ka farak khud mehsoos karein.",
  thanksQuote: "“Har ank ek sanket hai — jo use samajh leta hai, wahi apna samay apne haath mein le leta hai.”",
  brandTagline: "Har Ank ke Rahasye",
  heroNote: "Chaldean + Indian (Lo Shu) numerology · janm tarikh, samay aur sthaan par aadharit",
  formTitle: "Apni Janm Jaankari Bharein",
  formNote:
    "Poora analysis aapke janm ki tarikh, samay aur sthaan — teeno ke hisaab se banta hai. Samay Indian Standard Time (IST, UTC+5:30) mein liya jaata hai.",
  language: "Report ki Bhasha",
  languageNote: "Poora report isi bhasha mein banega.",
  fullName: "Poora Naam",
  dob: "Janm Tarikh",
  time: "Janm Samay",
  timezone: "Time Zone",
  timezoneValue: "Indian Standard Time (IST) · UTC+5:30 · Asia/Kolkata",
  gender: "Ling",
  male: "Purush",
  female: "Mahila",
  place: "Janm Sthan",
  detect: "Detect",
  searching: "Dhoondh rahe hain…",
  mobile: "Mobile Number",
  email: "Email",
  submit: "Mera Poora Analysis Banayein",
  required: "Sabhi * wale fields bharna zaroori hai — analysis date, time aur place teeno par aadharit hai.",
  invalidMobile: "Mobile number mein kam se kam 10 ank hone chahiye.",
  invalidEmail: "Email sahi format mein likhein (jaise naam@gmail.com).",
  identityCard: "Aapka Ank Parichay",
  birth: "Janm",
  placeLabel: "Sthan",
  basics: "Basics — Pehle Yeh Samajh Lein",
  meaning19: "1 se 9 ka matlab",
  formula: "Formula",
  whatIsChart: "Birth chart kya hai",
  chartNote:
    "Lo Shu ka 3×3 chart — har khaane ka apna ank hota hai. Aapke DOB ke ank + Driver, Conductor aur Kua inhi khaano mein rakhe jaate hain.",
  chartCaption: "Lo Shu ka standard 3×3 chart",
  whatArePlanes: "Planes kya hote hain",
  planesNote:
    "Plane matlab chart ki ek poori line — row, column ya diagonal — jisme teeno ank maujood hon. Neeche har plane ka chart:",
  whatIsYoga: "Yoga kya hai",
  yogaNote: "Chart mein bane khaas combinations jo kisi ek kshetra (naam, dhan, buddhi) mein zyada shakti dete hain.",
  yourAnalysis: "Yeh Aapka Analysis",
  driver: "Driver (Mulank)",
  conductor: "Conductor (Bhagyank)",
  kua: "Kua",
  behavesAs: "jaisa",
  birthChart: "Birth Chart (Lo Shu)",
  missing: "Missing",
  repeated: "Repeated",
  none: "koi nahi",
  lottery: "Paramatma ki Lottery",
  lotterySub: "Jo ank DOB mein nahi the par Driver/Conductor/Kua se chart mein aa gaye",
  lotteryNote: "Circle wale ank Paramatma ki Lottery se aaye hain.",
  lotteryEmpty: "Is chart mein koi extra ank nahi aaya.",
  goodDirs: "Shubh dishayein",
  element: "tattva",
  compatTitle: "Driver + Conductor Tal-mel",
  luckyBadNumbers: "Lucky aur Bad Numbers",
  luckyBadSub: "Driver + Conductor milakar",
  lucky: "Lucky",
  bad: "Bad",
  colorsTitle: "Lucky aur Bad Colours",
  luckyColors: "Lucky colours",
  badColors: "Bad colours",
  colorsNote: "Important din par lucky colour pehnein, bad colour ki badi cheez se bachein.",
  strengths: "Strengths",
  weaknesses: "Weaknesses",
  yogasTitle: "Aapke Yogas",
  noYoga: "Is chart mein koi poora yoga nahi bana.",
  nameNum: "Naam Numerology (Chaldean)",
  mobileNum: "Mobile Numerology",
  mobileNote: "Pair-by-pair vistrit asar Full Life Report mein diya gaya hai.",
  fullLifeReport: "Full Life Report",
  page: "Page",
  analysisBy: "Analysis by",
  getFullReport: "Get Full Report — Pura Vistrit Report Dekhein",
  downloadPdf: "PDF Download Karein",
  newReport: "Nayi Kundli Banayein",
  printBlocked: "Browser ne naya window rok diya — popup allow karke phir se try karein.",
  coverKicker: "Personal Numerology Analysis Report",
  coverNote:
    "Chaldean aur Lo Shu numerology ka milaan — birth chart, planes, yogas, lucky numbers, colours, jeevan ke chaar padaav, career, dhan, rishte aur saal-dar-saal ka vistrit vishleshan.",
  coverName: "Name",
  coverDob: "Date of Birth",
  coverTime: "Time of Birth",
  coverDay: "Day",
  coverPlace: "Place of Birth",
  coverMobile: "Mobile Number",
  coverEmail: "Email",
  coverGeneratedOn: "Report generated on",
  timeNumber: "Time number",
  lecTitle: "Lucky · Enemy · Neutral Number Chart",
  lecNumber: "Ank",
  lecLucky: "Lucky (Mitra)",
  lecEnemy: "Enemy (Shatru)",
  lecNeutral: "Neutral (Sam)",
  lecNote: "Reference chart — har ank ke lucky, enemy aur neutral ank isi report mein use hue hain.",
  calcTitle: "Calculation — Driver, Conductor aur Kua",
  calcDriverLabel: "Driver (Mulank) = janm ki tarikh ka ank jod",
  calcConductorLabel: "Conductor (Bhagyank) = poori janm tarikh (dd + mm + yyyy) ka ank jod",
  calcKuaLabel: "Kua = janm varsh ka ank jod, phir Purush: 11 − yog · Mahila: 4 + yog",
  calcNote: "Har jod ko 1 se 9 tak reduce kiya jaata hai.",
  calcBasicTitle: "Formula — Driver, Conductor aur Kua",
  calcFormulaDriver: "Driver (Mulank) = janm tarikh (dd) ke ank ka jod → 1–9. Jaise 29 → 2 + 9 = 11 → 1 + 1 = 2.",
  calcFormulaConductor: "Conductor (Bhagyank) = poori janm tarikh dd + mm + yyyy ke sabhi ank ka jod → 1–9. Jaise 29.08.1994 → 2+9+0+8+1+9+9+4 = 42 → 4 + 2 = 6.",
  calcFormulaKua: "Kua = janm varsh ke ank ka jod → 1–9, phir Purush: 11 − yog, Mahila: 4 + yog (9 se bada ho to phir se jod). Kua 5 ki apni disha nahi — Purush ke liye 2, Mahila ke liye 8 lagu hota hai.",
};

export const planets: Record<number, string> = {
  1: "Surya",
  2: "Chandra",
  3: "Guru (Brihaspati)",
  4: "Rahu",
  5: "Budh",
  6: "Shukra",
  7: "Ketu",
  8: "Shani",
  9: "Mangal",
};

export const weekdays = ["Ravivaar", "Somvaar", "Mangalvaar", "Budhvaar", "Guruvaar", "Shukravaar", "Shanivaar"];
export const dayLords = ["Surya", "Chandra", "Mangal", "Budh", "Guru", "Shukra", "Shani"];

export const dayParts: Record<DayPartKey, string> = {
  lateNight: "Raat ka aakhri pehar",
  morning: "Subah",
  afternoon: "Dopahar",
  evening: "Shaam",
  night: "Raat",
};

export const months = [
  "January", "February", "March", "April", "May", "June",
  "July", "August", "September", "October", "November", "December",
];

export const colors: Record<ColorKey, string> = {
  golden: "Sunehra (Golden)",
  orange: "Narangi",
  yellow: "Peela",
  deepBlue: "Gehra Neela",
  blackSlate: "Kaala-Sleti",
  white: "Safed",
  cream: "Kreem (Halka Peela-Safed)",
  silver: "Chandi Jaisa (Silver)",
  deepRed: "Gehra Laal",
  slate: "Sleti",
  saffron: "Kesari",
  deepBrown: "Gehra Bhura",
  grey: "Dhusar (Grey)",
  electricBlue: "Chamkeela Neela",
  khaki: "Mitti Rang (Khaki)",
  green: "Hara",
  turquoise: "Firozi",
  lightGrey: "Halka Dhusar",
  pink: "Gulabi",
  lightBlue: "Halka Neela",
  chestnut: "Gehra Kathai",
  lightGreen: "Halka Hara",
  smokyGrey: "Dhuaan Jaisa Dhusar",
  blue: "Neela",
  deepGreen: "Gehra Hara",
  red: "Laal",
  deepSaffron: "Gehra Kesari",
  coral: "Moonga (Coral)",
};

export const dirs: Record<DirKey, string> = {
  N: "Uttar",
  NE: "Uttar-Purv",
  E: "Purv",
  SE: "Dakshin-Purv",
  S: "Dakshin",
  SW: "Dakshin-Paschim",
  W: "Paschim",
  NW: "Uttar-Paschim",
};

export const rel: Record<RelKey, string> = {
  mitra: "mitra",
  shatru: "shatru",
  sam: "sam",
};

export const numbers: Record<number, NumData> = {
  1: {
    planet: "Surya",
    title: "Leader ka Ank",
    short: "Aap apni marzi ke maalik hain — jahan khade hote hain wahan direction aap hi decide karte hain.",
    keywords: ["Leadership", "Aatm-vishwas", "Pehchaan", "Nayi shuruaat"],
    strengths: [
      "Faisla lene ki taakat — dusron ke bharose par nahi rukte.",
      "Original soch, naye raste banane ki himmat.",
      "Zimmedari uthate hain, team aap par bharosa karti hai.",
      "Izzat aur naam apne dam par kamate hain.",
      "Crisis mein sabse pehle stand lene wale aap hote hain.",
    ],
    weaknesses: [
      "Ego jaldi hurt hota hai, jhukna mushkil lagta hai.",
      "Adesh dene ki aadat rishton mein doori la sakti hai.",
      "Advice lene se pehle hi faisla kar lete hain.",
      "Akelapan mehsoos hone par mood off ho jata hai.",
    ],
    career: ["Business owner", "Government/administration", "Brand aur marketing", "Consulting", "Politics ya public role"],
    money: ["Kamai achhi, par status pe kharcha zyada.", "Apne naam ki company/asset se stability aati hai."],
    love: ["Partner ko space dena zaroori hai.", "Dominating tone se bachein, warna gharelu tension banti hai."],
    health: ["Dil, aankh aur BP ka dhyan rakhein.", "Subah ki dhoop aur walk zaroori."],
    remedy: ["Surya ko jal arpan karein.", "Ravivaar ko gehun/gud daan karein."],
  },
  2: {
    planet: "Chandra",
    title: "Mann aur Bhavna ka Ank",
    short: "Aapki sabse badi taakat sensitivity hai — logon ka mood aap bina bole samajh lete hain.",
    keywords: ["Sahyog", "Kalpana", "Bhavna", "Diplomacy"],
    strengths: [
      "Logon ko jodne ki natural kala.",
      "Imagination aur creative soch bahut strong.",
      "Team mein peace maker ka role.",
      "Intuition aksar sach nikalta hai.",
      "Ghar-parivaar ke liye samarpit.",
    ],
    weaknesses: [
      "Mood swings — ek din josh, doosre din udaasi.",
      "Overthinking se decision late ho jata hai.",
      "Rejection dil pe le lete hain.",
      "Na keh paane ki aadat.",
    ],
    career: ["Counselling", "HR aur PR", "Art, music, writing", "Hospitality", "Water/dairy related business"],
    money: ["Paisa aata hai par sambhaal ke rakhna sikhna padta hai.", "Partnership mein kaam achha chalta hai."],
    love: ["Emotional security chahiye hoti hai.", "Partner ki taarif se aap khil uthte hain."],
    health: ["Neend, pet aur anxiety par dhyan.", "Paani zyada piyein, chandra-shanti helpful."],
    remedy: ["Somvaar ko safed cheez daan karein.", "Chandi dharan karein."],
  },
  3: {
    planet: "Guru (Brihaspati)",
    title: "Gyaan aur Vistaar ka Ank",
    short: "Aapke paas gyaan, guidance aur baat rakhne ki kala hai — log aapse seekhne aate hain.",
    keywords: ["Gyaan", "Guru-tattva", "Discipline", "Expression"],
    strengths: [
      "Padhaai, teaching aur guidance mein kamaal.",
      "Baat ko simple bana kar samjha dete hain.",
      "Positive soch aur dharm/values par pakad.",
      "Mehnat ka phal dher saara respect ke roop mein.",
      "Sahi-galat ka strong sense.",
    ],
    weaknesses: [
      "Zyada advice dene ki aadat.",
      "Apni baat ko hi sahi maanna.",
      "Kharcha bade level par ho jata hai.",
      "Kaam ko perfect banane ke chakkar mein delay.",
    ],
    career: ["Teaching aur training", "Law", "Finance/banking", "Content aur speaking", "Astrology/counselling"],
    money: ["Steady income, savings mein anushasan chahiye.", "Education ya knowledge se paisa banta hai."],
    love: ["Partner mein respect aur samajh dhoondhte hain.", "Lecture kam, sunna zyada — yahi formula hai."],
    health: ["Liver, weight aur sugar ka dhyan.", "Meetha kam karein."],
    remedy: ["Guruvaar ko peeli daal/kesari daan.", "Guru mantra jaap."],
  },
  4: {
    planet: "Rahu",
    title: "Alag Soch ka Ank",
    short: "Aap system ko alag nazar se dekhte hain — jahan sab rukte hain wahan aapko raasta dikhta hai.",
    keywords: ["Innovation", "Rebel", "Technology", "Risk"],
    strengths: [
      "Out-of-the-box soch, unconventional solutions.",
      "Technology aur digital duniya mein tez.",
      "Sangharsh se ghabrate nahi.",
      "Networking capability strong.",
      "Detail mein galti pakad lete hain.",
    ],
    weaknesses: [
      "Mann bechain rehta hai, sthirta kam.",
      "Shortcut aur risk ka aakarshan.",
      "Logon par jaldi shak.",
      "Neend aur soch ka balance bigadta hai.",
    ],
    career: ["IT aur software", "Media aur editing", "Import-export", "Research", "Electrical/automobile"],
    money: ["Achanak labh aur achanak kharcha dono.", "Documented investment safe rehta hai."],
    love: ["Misunderstanding se rishte bigadte hain — clear baat karein.", "Partner ko apni soch process samjhayein."],
    health: ["Nervous system, skin aur neend.", "Screen time kam karein."],
    remedy: ["Shanivaar ko kambal/til daan.", "Rahu shanti ke liye jal-daan."],
  },
  5: {
    planet: "Budh",
    title: "Buddhi aur Communication ka Ank",
    short: "Aap dimaag se tez hain — baat, business aur balance teeno aapke haath mein hain.",
    keywords: ["Communication", "Business", "Freedom", "Adaptability"],
    strengths: [
      "Tez dimaag, jaldi seekhne ki kshamta.",
      "Baat-cheet se kaam nikaal lena.",
      "Business sense natural hai.",
      "Har situation mein adjust kar lete hain.",
      "Grid ka centre — sab ko jodne wali energy.",
    ],
    weaknesses: [
      "Ek jagah tikna mushkil.",
      "Zyada bolna kabhi nuksaan de deta hai.",
      "Jaldi bore ho jate hain.",
      "Multitasking se kaam adhura reh jata hai.",
    ],
    career: ["Sales aur marketing", "Trading/stock", "Media aur writing", "Accounts", "Travel business"],
    money: ["Multiple income sources banate hain.", "Speculation mein sambhal kar chalein."],
    love: ["Friendly nature, par commitment mein time lagta hai.", "Baat karne ki kala rishta bachati hai."],
    health: ["Skin, nerves aur digestion.", "Neend ka time fix rakhein."],
    remedy: ["Budhvaar ko hari cheez daan.", "Paudhe lagayein."],
  },
  6: {
    planet: "Shukra",
    title: "Prem aur Sundarta ka Ank",
    short: "Aapke aas-paas sundarta, aaraam aur pyaar khud ba khud jama hota hai.",
    keywords: ["Prem", "Luxury", "Kala", "Parivaar"],
    strengths: [
      "Artistic nazar — design, decor, style mein maahir.",
      "Log aapki company enjoy karte hain.",
      "Parivaar ko jodkar rakhte hain.",
      "Comfort aur beauty create karne ki kala.",
      "Negotiation mein narmi se jeet.",
    ],
    weaknesses: [
      "Aaram-pasand hone se kaam taal dete hain.",
      "Kharcha luxury par zyada.",
      "Emotional attachment se decision bigadta hai.",
      "Doosron ko khush rakhne mein khud thak jate hain.",
    ],
    career: ["Fashion aur design", "Beauty/wellness", "Event management", "Real estate interiors", "Food business"],
    money: ["Paisa aata bhi hai, jata bhi jaldi hai.", "Budget banane se badi bachat."],
    love: ["Romantic aur loyal, par expectation zyada.", "Chhoti tareef aapke rishte ki dawai hai."],
    health: ["Kidney, reproductive health, weight.", "Meetha aur late-night khana kam karein."],
    remedy: ["Shukravaar ko safed mithai daan.", "Saaf-suthra ghar Shukra ko balvaan karta hai."],
  },
  7: {
    planet: "Ketu",
    title: "Gehrai aur Sadhna ka Ank",
    short: "Aapke andar ek shaant researcher rehta hai jo har cheez ki jad tak jaana chahta hai.",
    keywords: ["Adhyatm", "Research", "Ekaant", "Intuition"],
    strengths: [
      "Gehri soch aur research capability.",
      "Adhyatmik jhukav aur strong intuition.",
      "Akele kaam karne ki taakat.",
      "Sach pakadne ki nazar.",
      "Sankat mein shaant reh pate hain.",
    ],
    weaknesses: [
      "Duniya se kat jaane ki aadat.",
      "Bhavnaayein khul kar nahi kehte.",
      "Shak aur confusion.",
      "Money matters mein laparwahi.",
    ],
    career: ["Research aur analytics", "Medicine/healing", "Spiritual work", "Photography", "Occult/astrology"],
    money: ["Paisa aata hai par track nahi rehta.", "Automatic saving set karein."],
    love: ["Deep bonding chahiye, surface baatein pasand nahi.", "Chuppi ko partner samajh nahi paata — bolein."],
    health: ["Immunity, allergy aur mental fatigue.", "Dhyan se nervous system shaant hota hai."],
    remedy: ["Kutte ko roti khilayein.", "Roz dhyan/meditation karein."],
  },
  8: {
    planet: "Shani",
    title: "Karm aur Nyay ka Ank",
    short: "Aapki safalta dheere aati hai par jab aati hai to jad-mazboot hoti hai.",
    keywords: ["Mehnat", "Anushasan", "Nyay", "Sthirta"],
    strengths: [
      "Anthak mehnat aur dheeraj.",
      "Zimmedari nibhane ka pakka swabhav.",
      "Structure aur system banane mein maahir.",
      "Lambi race ke ghode — der se par zabardast success.",
      "Nyay-priya, galat ke saamne khade ho jate hain.",
    ],
    weaknesses: [
      "Sangharsh zyada, phal der se.",
      "Bhavna chhupa lete hain.",
      "Zid aur rigidity.",
      "Negative soch ka daur aata hai.",
    ],
    career: ["Manufacturing", "Construction aur real estate", "Law aur judiciary", "Mining/iron", "Labour-heavy business"],
    money: ["Savings strong, par loan se door rahein.", "Property mein achha yog."],
    love: ["Loyalty pakki, expression kam — bol kar batayein.", "Partner ko waqt dena sabse bada tohfa hai."],
    health: ["Ghutne, joints, hawa-janit rog.", "Stretching aur dhoop zaroori."],
    remedy: ["Shanivaar ko til-tel aur kaale chane daan.", "Mazdooron/gareebon ki madad karein."],
  },
  9: {
    planet: "Mangal",
    title: "Shakti aur Sahas ka Ank",
    short: "Aapke andar ki aag aapko rukne nahi deti — himmat aapka sabse bada hathiyaar hai.",
    keywords: ["Sahas", "Energy", "Seva", "Josh"],
    strengths: [
      "Bahut zyada energy aur stamina.",
      "Himmat — mushkil kaam pehle uthate hain.",
      "Doosron ki madad ka jazba.",
      "Field aur action roles mein leadership.",
      "Jaldi recover karne ki taakat.",
    ],
    weaknesses: ["Gussa aur jaldbaazi.", "Bina soche bol dena.", "Argument mein pad jana.", "Impatience se nuksaan."],
    career: ["Defence/police", "Sports aur fitness", "Surgery", "Engineering", "Land aur property"],
    money: ["Kamai tez, kharcha bhi tez.", "Property mein invest fayda deta hai."],
    love: ["Passionate, par gusse par control zaroori.", "Maafi maang lena aapki jeet hai."],
    health: ["Blood, chot, acidity.", "Roz physical activity zaroori."],
    remedy: ["Mangalvaar ko masoor daal daan.", "Hanuman Chalisa paath."],
  },
};

export const meanings: string[] = [
  "1 — Surya: leadership, pehchaan, apna faisla.",
  "2 — Chandra: mann, bhavna, sahyog.",
  "3 — Guru: gyaan, discipline, expression.",
  "4 — Rahu: alag soch, technology, risk.",
  "5 — Budh: buddhi, business, balance.",
  "6 — Shukra: prem, kala, sukh-suvidha.",
  "7 — Ketu: adhyatm, research, ekaant.",
  "8 — Shani: mehnat, nyay, sthirta.",
  "9 — Mangal: sahas, energy, seva.",
];

export const missingRemedy: Record<number, string> = {
  1: "Roz subah Surya ko jal dein aur apne faislon ko likh kar confirm karein.",
  2: "Chandi ka chhota tukda paas rakhein, raat ko chandrama dekhein.",
  3: "Guruvaar vrat ya peeli cheez ka daan, roz 10 minute padhai.",
  4: "Ghar ke electronics saaf rakhein, Shanivaar ko kambal daan.",
  5: "Hari sabzi/paudhe daan, roz likhne ki aadat banayein.",
  6: "Ghar mein taaza phool rakhein, Shukravaar safed mithai daan.",
  7: "Roz 10 minute dhyan, kutte ko roti.",
  8: "Shanivaar til-tel daan, kaam ka schedule likh kar chalein.",
  9: "Mangalvaar Hanuman Chalisa, gusse par 10 second rule.",
};

export const compat: Record<RelKey, { verdict: string; points: string[] }> = {
  mitra: {
    verdict: "Shubh Jodi",
    points: [
      "Driver aur Conductor ek doosre ko support karte hain — soch aur karm ek line mein.",
      "Faisle jaldi lagte hain aur pachtawa kam hota hai.",
      "Career mein growth smooth, badi rukavat kam.",
      "Rishton mein aapka balance dusron ko bhi accha lagta hai.",
    ],
  },
  sam: {
    verdict: "Sthir Jodi",
    points: [
      "Na zyada support, na zyada takraav — result mehnat par depend karta hai.",
      "Planning likh kar karein to yeh combination bahut fayda deta hai.",
      "Mood ke hisaab se kaam karne se nuksaan hota hai, routine banayein.",
      "Sahi guidance milte hi speed badh jaati hai.",
    ],
  },
  shatru: {
    verdict: "Sangharsh Jodi",
    points: [
      "Andar do alag aawazein chalti hain — dil kuch aur, dimaag kuch aur.",
      "Faisla badal-badal kar samay chala jata hai.",
      "Mehnat zyada, credit der se — par lambi race mein jeet aapki hai.",
      "Driver + Conductor milakar chuna hua lucky number aur colour balance banata hai.",
    ],
  },
};

export const kua: Record<number, { element: string; trigram: string; msg: string }> = {
  1: { element: "Jal", trigram: "Kan", msg: "Bahav ke saath chalein, zid chhodein." },
  2: { element: "Prithvi", trigram: "Kun", msg: "Sthirta aapki shakti hai." },
  3: { element: "Kaath", trigram: "Chen", msg: "Nayi shuruaat ka samay hai." },
  4: { element: "Kaath", trigram: "Sun", msg: "Rishton se raaste khulenge." },
  5: { element: "Prithvi", trigram: "Madhya", msg: "Kendra mein rahein, santulan banaye rakhein." },
  6: { element: "Dhatu", trigram: "Chien", msg: "Netritva sweekar karein." },
  7: { element: "Dhatu", trigram: "Tui", msg: "Khushi baantne se badhti hai." },
  8: { element: "Prithvi", trigram: "Ken", msg: "Dheeraj hi aapka dhan hai." },
  9: { element: "Agni", trigram: "Li", msg: "Apni roshni chhupayein nahi." },
};

export const planes = {
  mental: { label: "Mental Plane (4-9-2)", meaning: "Soch, planning aur dimaagi taakat ka plane." },
  emotional: { label: "Emotional Plane (3-5-7)", meaning: "Bhavnaayein, rishte aur balance ka plane." },
  practical: { label: "Practical Plane (8-1-6)", meaning: "Kaam, execution aur zameeni result ka plane." },
  thought: { label: "Thought Plane (4-3-8)", meaning: "Memory, ideas aur detail ka plane." },
  will: { label: "Will Plane (9-5-1)", meaning: "Ichha-shakti aur determination ka plane." },
  action: { label: "Action Plane (2-7-6)", meaning: "Karm, seva aur creative action ka plane." },
  golden: { label: "Golden Yoga / Rajyoga (4-5-6)", meaning: "Bada naam, position aur success ka diagonal." },
  silver: { label: "Silver Yoga (2-5-8)", meaning: "Paisa, stability aur dheeraj ka diagonal." },
};

export const personalYear: Record<number, { theme: string; points: string[] }> = {
  1: {
    theme: "Nayi Shuruaat ka Saal",
    points: [
      "Naya kaam, naya plan ya nayi jagah — beej bone ka saal hai.",
      "Jo faisla is saal lenge uska asar agle 9 saal chalega.",
      "Purane bekaar rishte/kaam chhodne ka sahi samay.",
      "Health aur confidence dono upar rahenge.",
      "Akele nirnay lein, par likh kar plan banayein.",
    ],
  },
  2: {
    theme: "Sabr aur Sath ka Saal",
    points: [
      "Jaldbaazi nuksaan degi — dheere chalna hi jeet hai.",
      "Partnership, shaadi aur team-work ke liye achha saal.",
      "Emotional utaar-chadhav zyada, neend ka dhyan rakhein.",
      "Purane kaam ko poora karne par focus.",
      "Baat-cheet se hi vivad sulajhenge.",
    ],
  },
  3: {
    theme: "Vistaar aur Pehchaan ka Saal",
    points: [
      "Naam aur network dono badhenge.",
      "Creative kaam, padhai aur content mein safalta.",
      "Kharcha badh sakta hai — budget banayein.",
      "Log aapki salah maangenge.",
      "Yatra aur naye contacts fayda denge.",
    ],
  },
  4: {
    theme: "Mehnat aur Neev ka Saal",
    points: [
      "Result dikhne se pehle mehnat maangi jaayegi.",
      "Documents, property aur legal kaam theek karein.",
      "Shortcut se door rahein.",
      "Sehat aur neend ka routine banayein.",
      "Jo is saal jamega woh lamba chalega.",
    ],
  },
  5: {
    theme: "Badlav aur Gati ka Saal",
    points: [
      "Job change, shifting ya naya vistaar sambhav.",
      "Communication aur marketing se labh.",
      "Chanchalta zyada — ek target par tike rahein.",
      "Yatra ke yog prabal.",
      "Naya seekhne ka best saal.",
    ],
  },
  6: {
    theme: "Parivaar aur Zimmedari ka Saal",
    points: [
      "Ghar, rishte aur responsibility centre mein rahenge.",
      "Shaadi, ghar sajaana ya property ka yog.",
      "Sehat par kharcha ho sakta hai.",
      "Kisi apne ki madad karni padegi.",
      "Kala aur sundarta se juda kaam chalega.",
    ],
  },
  7: {
    theme: "Antar-mann aur Gyaan ka Saal",
    points: [
      "Bahar se dheema, andar se sabse bada growth saal.",
      "Padhai, research aur adhyatm ka samay.",
      "Bhid se door rahkar plan banayein.",
      "Bade financial risk se bachein.",
      "Purane sawalon ke jawab milenge.",
    ],
  },
  8: {
    theme: "Karm aur Dhan ka Saal",
    points: [
      "Mehnat ka phal paisa aur position ke roop mein.",
      "Business, property aur bade sauda ke yog.",
      "Anushasan chhodne par nuksaan bhi bada.",
      "Legal aur tax kaam time par karein.",
      "Netritva ka mauka milega.",
    ],
  },
  9: {
    theme: "Poornta aur Vidaai ka Saal",
    points: [
      "Purana chapter band hoga, naya agle saal khulega.",
      "Jo cheezein bekar hain unhe chhodna hi labh hai.",
      "Seva aur daan se rukavatein hategi.",
      "Bade naye investment ko agle saal tak taalein.",
      "Emotional clearing ka saal — halka mehsoos karenge.",
    ],
  },
};

export const personalMonth: Record<number, string> = {
  1: "nayi shuruaat — naya kaam, naya plan shuru karein.",
  2: "sabr aur sahyog — partnership aur baat-cheet se kaam banega.",
  3: "expression aur network — logon se milna aur creative kaam fayda dega.",
  4: "mehnat aur documentation — neev pakki karne ka mahina.",
  5: "badlav aur gati — travel, marketing aur naye mauke.",
  6: "parivaar aur zimmedari — ghar, rishte aur sehat par kharcha.",
  7: "andar ki taiyari — planning, padhai, bade risk se door.",
  8: "paisa aur position — deal, payment aur bade faisle ka mahina.",
  9: "poornta — purana kaam khatam karein, naya agle mahine.",
};

export const monthAction: Record<number, string> = {
  1: "Is mahine ek nayi cheez shuru karein.",
  2: "Is mahine kisi ke saath milkar kaam karein.",
  3: "Is mahine apna kaam logon ke saamne rakhein.",
  4: "Is mahine kagzi kaam aur hisaab theek karein.",
  5: "Is mahine ek naya skill ya naya market try karein.",
  6: "Is mahine parivaar ko time dein.",
  7: "Is mahine plan banayein, bada risk na lein.",
  8: "Is mahine payment aur bade faisle nipta lein.",
  9: "Is mahine adhoore kaam poore karein.",
};
