// English base data (numbers, kua, personal year/month, labels).
import type { ColorKey, DirKey, DayPartKey, NumData, RelKey } from "../types";

export const ui: Record<string, string> = {
  printedOn: "Printed on",
  languageSwitchNote: "You can switch the language any time before you export the PDF.",
  kua5Note: "Kua 5 has no direction of its own — its equivalent Kua applies for Direction, Vastu and Energy.",
  thanksTitle: "Thank You",
  thanksHello: "Dear",
  thanksBody: "thank you for trusting NAMAANK. This report has been prepared with great care, mapping your name, date, time and place of birth onto the classical rules of numbers.",
  thanksBody2: "Numbers only show the road — walking it is your work. The remedies here are simple, yet practised steadily for 40 days their effect is unmistakable.",
  thanksQuote: "“Every number is a signal — the one who reads it takes his own time into his own hands.”",
  brandTagline: "The Secrets of Every Number",
  heroNote: "Chaldean + Indian (Lo Shu) numerology · based on your birth date, time and place",
  formTitle: "Enter Your Birth Details",
  formNote:
    "Your complete analysis is built from your birth date, time and place — all three together. Time is taken in Indian Standard Time (IST, UTC+5:30).",
  language: "Report Language",
  languageNote: "The full report will be generated in this language.",
  fullName: "Full Name",
  dob: "Date of Birth",
  time: "Time of Birth",
  timezone: "Time Zone",
  timezoneValue: "Indian Standard Time (IST) · UTC+5:30 · Asia/Kolkata",
  gender: "Gender",
  male: "Male",
  female: "Female",
  place: "Place of Birth",
  detect: "Detect",
  searching: "Searching…",
  mobile: "Mobile Number",
  email: "Email",
  submit: "Generate My Full Analysis",
  required: "All fields marked * are required — the analysis is based on date, time and place together.",
  invalidMobile: "The mobile number must have at least 10 digits.",
  invalidEmail: "Please enter a valid email format (e.g. name@gmail.com).",
  identityCard: "Your Number Identity",
  birth: "Birth",
  placeLabel: "Place",
  basics: "The Basics — Understand This First",
  meaning19: "What 1 to 9 Mean",
  formula: "Formula",
  whatIsChart: "What is the Birth Chart",
  chartNote:
    "The Lo Shu 3×3 chart — every cell carries its own number. The digits from your DOB, along with your Driver, Conductor and Kua numbers, are placed in these cells.",
  chartCaption: "The standard 3×3 Lo Shu chart",
  whatArePlanes: "What are Planes",
  planesNote:
    "A plane is one complete line in the chart — a row, column or diagonal — where all three numbers are present. Below is the chart for each plane:",
  whatIsYoga: "What is a Yoga",
  yogaNote: "Special combinations formed in the chart that give extra strength in one area of life (name, wealth, intellect).",
  yourAnalysis: "Your Analysis",
  driver: "Driver Number",
  conductor: "Conductor Number",
  kua: "Kua",
  behavesAs: "behaves like",
  birthChart: "Birth Chart (Lo Shu)",
  missing: "Missing",
  repeated: "Repeated",
  none: "none",
  lottery: "The Divine Lottery",
  lotterySub: "Numbers that were not in your DOB but entered the chart via Driver/Conductor/Kua",
  lotteryNote: "Circled numbers came into the chart through the Divine Lottery.",
  lotteryEmpty: "No extra numbers entered this chart.",
  goodDirs: "Favourable directions",
  element: "element",
  compatTitle: "Driver + Conductor Compatibility",
  luckyBadNumbers: "Lucky and Bad Numbers",
  luckyBadSub: "Driver + Conductor combined",
  lucky: "Lucky",
  bad: "Bad",
  colorsTitle: "Lucky and Bad Colours",
  luckyColors: "Lucky colours",
  badColors: "Bad colours",
  colorsNote: "Wear your lucky colour on important days, and avoid big items in your bad colour.",
  strengths: "Strengths",
  weaknesses: "Weaknesses",
  yogasTitle: "Your Yogas",
  noYoga: "No complete yoga is formed in this chart.",
  nameNum: "Name Numerology (Chaldean)",
  mobileNum: "Mobile Numerology",
  mobileNote: "A detailed pair-by-pair analysis is given in the Full Life Report.",
  fullLifeReport: "Full Life Report",
  page: "Page",
  analysisBy: "Analysis by",
  getFullReport: "Get Full Report",
  downloadPdf: "Download PDF",
  newReport: "Create a New Chart",
  printBlocked: "Your browser blocked the new window — please allow popups and try again.",
  coverKicker: "Personal Numerology Analysis Report",
  coverNote:
    "A blend of Chaldean and Lo Shu numerology — birth chart, planes, yogas, lucky numbers, colours, the four stages of life, career, wealth, relationships and a detailed year-by-year analysis.",
  coverName: "Name",
  coverDob: "Date of Birth",
  coverTime: "Time of Birth",
  coverDay: "Day",
  coverPlace: "Place of Birth",
  coverMobile: "Mobile Number",
  coverEmail: "Email",
  coverGeneratedOn: "Report generated on",
  timeNumber: "Time number",
  lecTitle: "Lucky · Enemy · Neutral Number Chart",
  lecNumber: "Number",
  lecLucky: "Lucky (Friend)",
  lecEnemy: "Enemy",
  lecNeutral: "Neutral",
  lecNote: "Reference chart — the lucky, enemy and neutral numbers used throughout this report.",
  calcTitle: "Calculation — Driver, Conductor and Kua",
  calcDriverLabel: "Driver (Mulank) = digit sum of the birth date",
  calcConductorLabel: "Conductor (Bhagyank) = digit sum of the full birth date (dd + mm + yyyy)",
  calcKuaLabel: "Kua = digit sum of the birth year, then Male: 11 − sum · Female: 4 + sum",
  calcNote: "Every sum is reduced down to a single digit 1–9.",
  calcBasicTitle: "Formula — Driver, Conductor and Kua",
  calcFormulaDriver: "Driver (Mulank) = digit sum of the birth day (dd) reduced to 1–9. E.g. 29 → 2 + 9 = 11 → 1 + 1 = 2.",
  calcFormulaConductor: "Conductor (Bhagyank) = digit sum of the full date dd + mm + yyyy reduced to 1–9. E.g. 29.08.1994 → 2+9+0+8+1+9+9+4 = 42 → 4 + 2 = 6.",
  calcFormulaKua: "Kua = digit sum of the birth year reduced to 1–9, then Male: 11 − sum, Female: 4 + sum (reduce again if above 9). Kua 5 has no direction of its own — it behaves as 2 for men and 8 for women.",
};

export const planets: Record<number, string> = {
  1: "Surya (Sun)",
  2: "Chandra (Moon)",
  3: "Guru (Jupiter)",
  4: "Rahu",
  5: "Budh (Mercury)",
  6: "Shukra (Venus)",
  7: "Ketu",
  8: "Shani (Saturn)",
  9: "Mangal (Mars)",
};

export const weekdays = ["Sunday", "Monday", "Tuesday", "Wednesday", "Thursday", "Friday", "Saturday"];
export const dayLords = ["Surya (Sun)", "Chandra (Moon)", "Mangal (Mars)", "Budh (Mercury)", "Guru (Jupiter)", "Shukra (Venus)", "Shani (Saturn)"];

export const dayParts: Record<DayPartKey, string> = {
  lateNight: "Late night",
  morning: "Morning",
  afternoon: "Afternoon",
  evening: "Evening",
  night: "Night",
};

export const months = [
  "January", "February", "March", "April", "May", "June",
  "July", "August", "September", "October", "November", "December",
];

export const colors: Record<ColorKey, string> = {
  golden: "Golden",
  orange: "Orange",
  yellow: "Yellow",
  deepBlue: "Deep Blue",
  blackSlate: "Black-Slate",
  white: "White",
  cream: "Cream",
  silver: "Silver",
  deepRed: "Deep Red",
  slate: "Slate",
  saffron: "Saffron",
  deepBrown: "Deep Brown",
  grey: "Grey",
  electricBlue: "Electric Blue",
  khaki: "Khaki",
  green: "Green",
  turquoise: "Turquoise",
  lightGrey: "Light Grey",
  pink: "Pink",
  lightBlue: "Light Blue",
  chestnut: "Chestnut",
  lightGreen: "Light Green",
  smokyGrey: "Smoky Grey",
  blue: "Blue",
  deepGreen: "Deep Green",
  red: "Red",
  deepSaffron: "Deep Saffron",
  coral: "Coral",
};

export const dirs: Record<DirKey, string> = {
  N: "North",
  NE: "North-East",
  E: "East",
  SE: "South-East",
  S: "South",
  SW: "South-West",
  W: "West",
  NW: "North-West",
};

export const rel: Record<RelKey, string> = {
  mitra: "friend",
  shatru: "enemy",
  sam: "neutral",
};

export const numbers: Record<number, NumData> = {
  1: {
    planet: "Surya (Sun)",
    title: "The Number of the Leader",
    short: "You are the master of your own will — wherever you stand, you decide the direction.",
    keywords: ["Leadership", "Confidence", "Identity", "New beginnings"],
    strengths: [
      "The power to decide — you don't wait on others to move.",
      "Original thinking and the courage to carve new paths.",
      "You take responsibility, and the team trusts you.",
      "You earn respect and reputation on your own merit.",
      "You are usually the first to take a stand in a crisis.",
    ],
    weaknesses: [
      "Your ego gets hurt easily, bending feels difficult.",
      "A habit of giving orders can create distance in relationships.",
      "You often decide before taking advice.",
      "Loneliness can quickly sour your mood.",
    ],
    career: ["Business owner", "Government/administration", "Branding and marketing", "Consulting", "Politics or public roles"],
    money: ["Good earnings, but spending on status tends to be high.", "Stability comes from assets and companies built in your own name."],
    love: ["Giving your partner space is essential.", "Avoid a dominating tone, or it creates tension at home."],
    health: ["Take care of your heart, eyes and blood pressure.", "Morning sunlight and walking are essential."],
    remedy: ["Offer water to Surya (the Sun).", "Donate wheat/jaggery on Sundays."],
  },
  2: {
    planet: "Chandra (Moon)",
    title: "The Number of Heart and Emotion",
    short: "Your greatest strength is sensitivity — you understand people's moods without a word being spoken.",
    keywords: ["Cooperation", "Imagination", "Emotion", "Diplomacy"],
    strengths: [
      "A natural gift for bringing people together.",
      "Very strong imagination and creative thinking.",
      "The peacemaker's role within any team.",
      "Your intuition often turns out to be right.",
      "Deeply devoted to home and family.",
    ],
    weaknesses: [
      "Mood swings — enthusiasm one day, sadness the next.",
      "Overthinking delays decisions.",
      "You take rejection to heart.",
      "A habit of not being able to say no.",
    ],
    career: ["Counselling", "HR and PR", "Art, music, writing", "Hospitality", "Water/dairy-related business"],
    money: ["Money comes, but you must learn to hold on to it.", "Work goes well in partnerships."],
    love: ["You need emotional security.", "A partner's appreciation makes you glow."],
    health: ["Pay attention to sleep, stomach and anxiety.", "Drink more water; lunar remedies help."],
    remedy: ["Donate white items on Mondays.", "Wear silver."],
  },
  3: {
    planet: "Guru (Jupiter)",
    title: "The Number of Knowledge and Growth",
    short: "You carry wisdom, guidance and the gift of expression — people come to you to learn.",
    keywords: ["Knowledge", "Wisdom", "Discipline", "Expression"],
    strengths: [
      "Excellent at teaching, training and guiding others.",
      "You can explain complex things simply.",
      "Positive thinking and a strong grip on values/dharma.",
      "Hard work is repaid with plenty of respect.",
      "A strong sense of right and wrong.",
    ],
    weaknesses: [
      "A tendency to give too much advice.",
      "Believing only your own view is correct.",
      "Spending tends to happen on a grand scale.",
      "Delays caused by wanting everything to be perfect.",
    ],
    career: ["Teaching and training", "Law", "Finance/banking", "Content and speaking", "Astrology/counselling"],
    money: ["Steady income, but discipline in savings is needed.", "Money is made through education or knowledge."],
    love: ["You look for respect and understanding in a partner.", "Less lecturing, more listening — that's the formula."],
    health: ["Watch your liver, weight and sugar levels.", "Cut down on sweets."],
    remedy: ["Donate yellow lentils/saffron items on Thursdays.", "Chant the Guru mantra."],
  },
  4: {
    planet: "Rahu",
    title: "The Number of Unconventional Thinking",
    short: "You see the system from a different angle — where everyone else stops, you find a way through.",
    keywords: ["Innovation", "Rebel", "Technology", "Risk"],
    strengths: [
      "Out-of-the-box thinking and unconventional solutions.",
      "Quick with technology and the digital world.",
      "You are not afraid of struggle.",
      "Strong networking ability.",
      "You catch mistakes in detail that others miss.",
    ],
    weaknesses: [
      "The mind stays restless, with little stability.",
      "An attraction to shortcuts and risk.",
      "Quick to suspect others.",
      "A disturbed balance between sleep and overthinking.",
    ],
    career: ["IT and software", "Media and editing", "Import-export", "Research", "Electrical/automobile"],
    money: ["Sudden gains as well as sudden expenses.", "Documented investments are the safest for you."],
    love: ["Relationships suffer from misunderstandings — communicate clearly.", "Explain your thought process to your partner."],
    health: ["Watch your nervous system, skin and sleep.", "Reduce screen time."],
    remedy: ["Donate a blanket/sesame seeds on Saturdays.", "Offer water for peace from Rahu."],
  },
  5: {
    planet: "Budh (Mercury)",
    title: "The Number of Intellect and Communication",
    short: "You are sharp-minded — conversation, business and balance are all in your hands.",
    keywords: ["Communication", "Business", "Freedom", "Adaptability"],
    strengths: [
      "A sharp mind and the ability to learn quickly.",
      "Getting things done through good conversation.",
      "A natural sense for business.",
      "You adjust to any situation.",
      "The centre of the grid — an energy that connects everyone.",
    ],
    weaknesses: [
      "Difficulty staying in one place.",
      "Talking too much can sometimes cause harm.",
      "You get bored quickly.",
      "Multitasking can leave work unfinished.",
    ],
    career: ["Sales and marketing", "Trading/stocks", "Media and writing", "Accounts", "Travel business"],
    money: ["You create multiple sources of income.", "Be careful with speculation."],
    love: ["A friendly nature, but commitment takes time.", "Your gift for conversation saves the relationship."],
    health: ["Watch your skin, nerves and digestion.", "Keep your sleep schedule fixed."],
    remedy: ["Donate something green on Wednesdays.", "Plant a sapling."],
  },
  6: {
    planet: "Shukra (Venus)",
    title: "The Number of Love and Beauty",
    short: "Beauty, comfort and love naturally gather around you.",
    keywords: ["Love", "Luxury", "Art", "Family"],
    strengths: [
      "An artistic eye — skilled in design, decor and style.",
      "People genuinely enjoy your company.",
      "You hold the family together.",
      "A gift for creating comfort and beauty.",
      "You win negotiations through gentleness.",
    ],
    weaknesses: [
      "A love of comfort can lead to postponing work.",
      "Spending tends to lean toward luxury.",
      "Emotional attachment can cloud decisions.",
      "You wear yourself out trying to keep others happy.",
    ],
    career: ["Fashion and design", "Beauty/wellness", "Event management", "Real estate interiors", "Food business"],
    money: ["Money comes in, but also goes out quickly.", "Making a budget brings big savings."],
    love: ["Romantic and loyal, but expectations run high.", "A small compliment is the best medicine for your relationship."],
    health: ["Watch your kidneys, reproductive health and weight.", "Cut down on sweets and late-night eating."],
    remedy: ["Donate white sweets on Fridays.", "A clean, tidy home strengthens Shukra (Venus)."],
  },
  7: {
    planet: "Ketu",
    title: "The Number of Depth and Inner Practice",
    short: "A quiet researcher lives within you, always wanting to get to the root of things.",
    keywords: ["Spirituality", "Research", "Solitude", "Intuition"],
    strengths: [
      "Deep thinking and strong research ability.",
      "A spiritual inclination and strong intuition.",
      "The strength to work alone.",
      "An eye for catching the truth.",
      "You stay calm in a crisis.",
    ],
    weaknesses: [
      "A tendency to withdraw from the world.",
      "You don't express your feelings openly.",
      "Doubt and confusion.",
      "Carelessness with money matters.",
    ],
    career: ["Research and analytics", "Medicine/healing", "Spiritual work", "Photography", "Occult/astrology"],
    money: ["Money comes in, but you lose track of it.", "Set up automatic savings."],
    love: ["You need deep bonding, surface talk doesn't appeal.", "Your silence is hard for a partner to read — speak up."],
    health: ["Watch your immunity, allergies and mental fatigue.", "Meditation calms the nervous system."],
    remedy: ["Feed bread to dogs.", "Practise daily meditation."],
  },
  8: {
    planet: "Shani (Saturn)",
    title: "The Number of Action and Justice",
    short: "Your success comes slowly, but when it arrives, it is built on solid ground.",
    keywords: ["Hard work", "Discipline", "Justice", "Stability"],
    strengths: [
      "Tireless hard work and patience.",
      "A firm nature that honours responsibility.",
      "Skilled at building structure and systems.",
      "A long-distance runner — success comes late but is powerful.",
      "A love of justice; you stand up against wrong.",
    ],
    weaknesses: [
      "Struggle is high, and rewards come late.",
      "You hide your feelings.",
      "Stubbornness and rigidity.",
      "Periods of negative thinking.",
    ],
    career: ["Manufacturing", "Construction and real estate", "Law and judiciary", "Mining/iron", "Labour-intensive business"],
    money: ["Strong savings, but stay away from loans.", "Good prospects in property."],
    love: ["Loyalty is solid, but expression is low — say it out loud.", "Giving your partner time is the greatest gift."],
    health: ["Watch your knees, joints and wind-related ailments.", "Stretching and sunlight are essential."],
    remedy: ["Donate sesame oil and black gram on Saturdays.", "Help labourers and the needy."],
  },
  9: {
    planet: "Mangal (Mars)",
    title: "The Number of Strength and Courage",
    short: "The fire within you never lets you stop — courage is your greatest weapon.",
    keywords: ["Courage", "Energy", "Service", "Passion"],
    strengths: [
      "Very high energy and stamina.",
      "Courage — you take on the hard task first.",
      "A spirit of helping others.",
      "Leadership in field and action-based roles.",
      "The strength to recover quickly.",
    ],
    weaknesses: ["Anger and impulsiveness.", "Speaking without thinking.", "Getting drawn into arguments.", "Losses caused by impatience."],
    career: ["Defence/police", "Sports and fitness", "Surgery", "Engineering", "Land and property"],
    money: ["Earnings come fast, and so does spending.", "Investing in property pays off."],
    love: ["Passionate, but controlling your temper is essential.", "Asking for forgiveness is your victory."],
    health: ["Watch your blood, injuries and acidity.", "Daily physical activity is essential."],
    remedy: ["Donate red lentils on Tuesdays.", "Recite the Hanuman Chalisa."],
  },
};

export const meanings: string[] = [
  "1 — Surya (Sun): leadership, identity, independent decisions.",
  "2 — Chandra (Moon): heart, emotion, cooperation.",
  "3 — Guru (Jupiter): knowledge, discipline, expression.",
  "4 — Rahu: unconventional thinking, technology, risk.",
  "5 — Budh (Mercury): intellect, business, balance.",
  "6 — Shukra (Venus): love, art, comfort.",
  "7 — Ketu: spirituality, research, solitude.",
  "8 — Shani (Saturn): hard work, justice, stability.",
  "9 — Mangal (Mars): courage, energy, service.",
];

export const missingRemedy: Record<number, string> = {
  1: "Offer water to Surya (the Sun) every morning and write down your decisions to confirm them.",
  2: "Keep a small piece of silver with you, and look at the moon at night.",
  3: "Fast on Thursdays or donate something yellow; study for 10 minutes daily.",
  4: "Keep the electronics in your home clean, and donate a blanket on Saturdays.",
  5: "Donate green vegetables/plants, build a daily writing habit.",
  6: "Keep fresh flowers at home, donate white sweets on Fridays.",
  7: "Meditate for 10 minutes daily, feed bread to dogs.",
  8: "Donate sesame oil on Saturdays, and keep a written work schedule.",
  9: "Recite the Hanuman Chalisa on Tuesdays; follow the 10-second rule when angry.",
};

export const compat: Record<RelKey, { verdict: string; points: string[] }> = {
  mitra: {
    verdict: "A Favourable Pairing",
    points: [
      "The Driver and Conductor support each other — thought and action move in one line.",
      "Decisions come quickly and regret stays low.",
      "Career growth stays smooth, with fewer major obstacles.",
      "The balance you bring to relationships is appreciated by others too.",
    ],
  },
  sam: {
    verdict: "A Stable Pairing",
    points: [
      "Neither much support nor much conflict — the result depends on effort.",
      "This combination pays off well when plans are put in writing.",
      "Working moody rather than by routine causes losses, so build a routine.",
      "With the right guidance, your speed picks up quickly.",
    ],
  },
  shatru: {
    verdict: "A Challenging Pairing",
    points: [
      "Two different voices run within you — the heart says one thing, the mind another.",
      "Time is lost as decisions keep changing.",
      "Effort is high and credit comes late — but you win in the long run.",
      "Choosing a lucky number and colour that combine Driver + Conductor creates balance.",
    ],
  },
};

export const kua: Record<number, { element: string; trigram: string; msg: string }> = {
  1: { element: "Water", trigram: "Kan", msg: "Flow with the current, let go of stubbornness." },
  2: { element: "Earth", trigram: "Kun", msg: "Stability is your strength." },
  3: { element: "Wood", trigram: "Chen", msg: "This is a time for new beginnings." },
  4: { element: "Wood", trigram: "Sun", msg: "Paths will open through relationships." },
  5: { element: "Earth", trigram: "Centre", msg: "Stay centred and maintain balance." },
  6: { element: "Metal", trigram: "Chien", msg: "Accept leadership when it comes." },
  7: { element: "Metal", trigram: "Tui", msg: "Happiness grows when it is shared." },
  8: { element: "Earth", trigram: "Ken", msg: "Patience is your true wealth." },
  9: { element: "Fire", trigram: "Li", msg: "Do not hide your light." },
};

export const planes = {
  mental: { label: "Mental Plane (4-9-2)", meaning: "The plane of thinking, planning and mental strength." },
  emotional: { label: "Emotional Plane (3-5-7)", meaning: "The plane of feelings, relationships and balance." },
  practical: { label: "Practical Plane (8-1-6)", meaning: "The plane of work, execution and real-world results." },
  thought: { label: "Thought Plane (4-3-8)", meaning: "The plane of memory, ideas and detail." },
  will: { label: "Will Plane (9-5-1)", meaning: "The plane of willpower and determination." },
  action: { label: "Action Plane (2-7-6)", meaning: "The plane of action, service and creative expression." },
  golden: { label: "Golden Yoga / Rajyoga (4-5-6)", meaning: "The diagonal of great name, position and success." },
  silver: { label: "Silver Yoga (2-5-8)", meaning: "The diagonal of money, stability and patience." },
};

export const personalYear: Record<number, { theme: string; points: string[] }> = {
  1: {
    theme: "The Year of New Beginnings",
    points: [
      "New work, new plans or a new place — this is the year to plant seeds.",
      "Decisions made this year will affect the next 9 years.",
      "The right time to let go of old, unproductive relationships or work.",
      "Both health and confidence will stay high.",
      "Make decisions on your own, but put your plans in writing.",
    ],
  },
  2: {
    theme: "The Year of Patience and Partnership",
    points: [
      "Rushing will cause losses — moving slowly is the real victory.",
      "A good year for partnerships, marriage and teamwork.",
      "Emotional ups and downs will be higher, so watch your sleep.",
      "Focus on completing old, pending work.",
      "Disputes will be resolved only through conversation.",
    ],
  },
  3: {
    theme: "The Year of Expansion and Recognition",
    points: [
      "Both your reputation and your network will grow.",
      "Success in creative work, studies and content.",
      "Expenses may rise — make a budget.",
      "People will come to you for advice.",
      "Travel and new contacts will prove beneficial.",
    ],
  },
  4: {
    theme: "The Year of Hard Work and Foundation",
    points: [
      "Effort will be required before results appear.",
      "Sort out documents, property and legal matters.",
      "Stay away from shortcuts.",
      "Build a routine for health and sleep.",
      "Whatever you build solidly this year will last long.",
    ],
  },
  5: {
    theme: "The Year of Change and Movement",
    points: [
      "A job change, relocation or new expansion is possible.",
      "Benefits from communication and marketing.",
      "Restlessness runs high — stay focused on one target.",
      "Strong chances for travel.",
      "The best year for learning something new.",
    ],
  },
  6: {
    theme: "The Year of Family and Responsibility",
    points: [
      "Home, relationships and responsibility take centre stage.",
      "Chances of marriage, home decoration or property.",
      "Expenses may arise around health.",
      "You may need to help a loved one.",
      "Work related to art and beauty will flow well.",
    ],
  },
  7: {
    theme: "The Year of Inner Reflection and Wisdom",
    points: [
      "Slow on the outside, but the biggest year of inner growth.",
      "A time for study, research and spiritual practice.",
      "Plan away from the crowd.",
      "Avoid major financial risks.",
      "Answers to old questions will be found.",
    ],
  },
  8: {
    theme: "The Year of Action and Wealth",
    points: [
      "The fruit of your hard work arrives as money and position.",
      "Chances for business, property and large deals.",
      "Losing discipline this year brings a bigger loss too.",
      "Handle legal and tax matters on time.",
      "An opportunity for leadership will arise.",
    ],
  },
  9: {
    theme: "The Year of Completion and Closure",
    points: [
      "An old chapter closes; a new one opens next year.",
      "Letting go of things that no longer serve you brings benefit.",
      "Service and charity will clear obstacles.",
      "Postpone major new investments until next year.",
      "A year of emotional clearing — you will feel lighter.",
    ],
  },
};

export const personalMonth: Record<number, string> = {
  1: "new beginnings — start new work, start new plans.",
  2: "patience and cooperation — partnership and conversation will get the work done.",
  3: "expression and networking — meeting people and creative work will pay off.",
  4: "hard work and documentation — a month to lay solid foundations.",
  5: "change and movement — travel, marketing and new opportunities.",
  6: "family and responsibility — spending on home, relationships and health.",
  7: "inner preparation — planning, study, staying away from big risks.",
  8: "money and position — a month for deals, payments and major decisions.",
  9: "completion — finish old work, start fresh next month.",
};

export const monthAction: Record<number, string> = {
  1: "Start something new this month.",
  2: "Work together with someone this month.",
  3: "Put your work in front of people this month.",
  4: "Sort out paperwork and accounts this month.",
  5: "Try a new skill or a new market this month.",
  6: "Give time to family this month.",
  7: "Make plans this month, avoid big risks.",
  8: "Settle payments and major decisions this month.",
  9: "Complete unfinished work this month.",
};
