// Hinglish full-life-report banks.
// Every line may use placeholders: {name} {driver} {conductor} {kua} {dp} {cp} {kp}
// {lucky} {bad} {lc1} {lc2} {bc1} {dir1} {dir2} {dir3} {weekday} {dayLord}
// {place} {time} {date} {missing} {repeated} {mobileSingle} {nameSingle} {verdict} {relText}
import type { PageKey, ReportPage } from "../types";

export const dyn: Record<string, string> = {
  intro: "{name}, aapka Driver {driver} ({dp}) batata hai ki aap andar se kaise hain: {driverShort}",
  conductorLine: "Conductor {conductor} ({cp}) batata hai ki duniya aapko kaise dekhti hai: {conductorShort}",
  relLine: 'Driver aur Conductor ka rishta "{relText}" hai — {verdict}.',
  kuaLine: "Kua {kuaEff} aapki disha aur urja ka control rakhta hai — element {element}, trigram {trigram}.",
  kua5: "Aapka janm-Kua 5 hai, jo apni koi disha nahi rakhta — isliye Disha, Vastu aur Urja ke liye Kua {kuaBehavesAs} hi lagu hota hai.",
  birthLine: "Janm tarikh {date} — din raat 12 baje badalta hai, isliye yahi aapki calculation date hai.",
  dayLine: "Janm {weekday} ko hua, jiska swami {dayLord} hai — swabhav mein {dayKeyword} ka rang gehra hai.",
  timeLine: "Janm samay {time} (IST) — {dayPart}, time number {timeNumber}.",
  placeLine: "Janm sthan: {place}.",
  luckyLine: "Aapke lucky numbers: {lucky}. Bachne wale numbers: {bad}.",
  colorLine: "Aapke lucky rang: {luckyColors}. Bachne wale rang: {badColors}.",
  dirLine: "Shubh dishayein: {dirsAll}. Kaam karte samay munh {dir1} ki taraf rakhein.",
  missingLine: "Aapke chart mein missing ank: {missing}.",
  noMissing: "Aapke chart mein koi ank missing nahi hai — yeh apne aap mein badi baat hai.",
  missingItem: "{n} ({planet}) missing — {weakness} Upay: {remedy}",
  repeatedLine: "Repeated ank: {repeated}.",
  noRepeated: "Koi ank repeat nahi hai — energy balanced hai.",
  repeatedItem: "{n} ({planet}) zyada hai — {weakness}",
  centre: "Grid ka centre 5: {state}",
  centreFull: "bhara hua — balance aur decision power achhi.",
  centreEmpty: "khaali — decisions mein confusion rehta hai, 5 ka upay karein.",
  lotteryLine: "Paramatma ki Lottery: {lottery} — yeh DOB mein nahi the par Driver/Conductor/Kua se chart mein aaye.",
  noLottery: "Paramatma ki Lottery is chart mein nahi bani.",
  planeItem: "{label}: {state}{meaning}",
  planeActive: "ACTIVE — ",
  planeIncomplete: "adhura — ",
  planeNeed: "{label} ke liye ank {cells} chahiye; aapke paas {have} hai.",
  activePlanes: "Aapke active planes: {list}.",
  noActivePlane: "Aapka koi plane poora active nahi — mehnat aur upay se kami puri hoti hai.",
  strengthDriver: "Driver {driver}: {text}",
  strengthConductor: "Conductor {conductor}: {text}",
  strengthKua: "Kua {kuaEff}: {text}",
  careerDriver: "Driver {driver} ke liye best lines: {list}.",
  careerConductor: "Conductor {conductor} ke liye best lines: {list}.",
  careerMix: "Dono milakar sabse strong option: {a} + {b} ka mel.",
  nameLine: "Poora naam: {fullName}. Chaldean compound {compound} → single {nameSingle} ({namePlanet}).",
  nameFirst: "First name number: {first}.",
  nameRelD: "Naam ka single {nameSingle} aur Driver {driver} ka rishta: {relName}.",
  nameRelC: "Naam ka single {nameSingle} aur Conductor {conductor} ka rishta: {relNameC}.",
  nameLetters: "Akshar-wise value: {letters}.",
  nameBad: "Naam ki vibration aapke bad numbers mein hai — spelling mein ek akshar ka halka badlav fayda dega.",
  nameGood: "Naam ki vibration support kar rahi hai, badlav ki zarurat nahi.",
  mobLine: "Mobile: {mobile} — total {mobTotal} → single {mobileSingle} ({mobPlanet}).",
  mobZeros: "Zeros: {zeros} — zero apne paas wale ank ka asar badha deta hai.",
  mobFirst: "Pehle 4 ank ka total {first4} — yeh aapki shuruaat ki energy hai.",
  mobLast: "Aakhri 4 ank ka total {last4} — yeh result ki energy hai.",
  mobRep: "Repeated digits: {rep} · Absent digits: {abs}.",
  mobRel: "Mobile single {mobileSingle} aur Driver {driver} ka rishta: {relMob}.",
  mobBad: "Mobile number ki vibration aapke khilaaf ja rahi hai — number badalne par kaam smooth hoga.",
  mobGood: "Mobile number aapke saath support kar raha hai.",
  pairItem: "{pair} ({sum} → {single}) · {rel} — {effect}",
  pairMitra: "Support karta hai, energy smooth chalti hai.",
  pairShatru: "Rukavat deta hai — kharcha ya tension badha sakta hai.",
  pairSam: "Neutral — na khaas fayda, na nuksaan.",
  pairCount: "Mitra jode: {m}, shatru jode: {s}, sam jode: {n}.",
  pairVerdictBad: "Shatru jode zyada hain — kaam ke liye doosra number rakhna behtar hoga.",
  pairVerdictGood: "Mitra jode zyada hain — yeh number aapke kaam ko support karta hai.",
  dayColor: "{day} ({lord}, ank {num}) — pehnein: {wear}. Bachein: {avoid}. {note}",
  dayColorGood: "Yeh din aapke lucky set mein hai, bade kaam isi din rakhein.",
  dayColorCare: "Is din safe rang par rahein aur risk wale faisle taalein.",
  yearCalc: "Calculation: janm ki tarikh aur mahina wahi, saal ki jagah {year} — {formula}.",
  yearTheme: "Personal Year {num}: {theme}",
  monthLine: "{month} {year} — Personal Month {num}: {meaning} {action}",
  yearStrong: "Is saal ka sabse strong mahina: {month}.",
  yearWeak: "Sabse sambhal kar chalne wala mahina: {month}.",
  yearRel: "Is saal Driver {driver} ke saath Personal Year {num} ka rishta: {rel}.",
  upayPrefix: "Upay: ",
  remedyBasis:
    "Yeh upay aapke naam, janm tarikh ({date}), samay ({time}) aur sthaan ({place}) ke aadhar par chune gaye hain.",
};

export const upay: string[] = [
  "Roz subah {lc1} rang ki koi ek cheez saath rakhein — {dp} ki urja sthir hoti hai.",
  "Har {weekday} ko {dayLord} se judi ek chhoti seva karein — jal, anna ya vastra daan.",
  "Ghar ki {dir1} disha mein ek saaf jagah banayein aur wahin baith kar 10 minute dhyan karein.",
  "Din ki shuruaat apne isht ka naam {luckyFirst} baar lekar karein.",
  "Missing ank {missingFirst} ke liye 40 din tak roz us ank ko 108 baar likhne ka abhyas karein.",
  "Important call ya meeting {lc2} rang ke kapdon mein karein.",
  "{bc1} rang ki badi cheez (curtain, bedsheet, bag) ghar se hata dein.",
  "Janm samay ({time}) ke aas-paas ka ek ghanta roz apne sabse zaroori kaam ke liye rakhein.",
  "{place} ki mitti se juda koi paudha ghar mein lagayein — jadd se jud jaate hain.",
  "Nayi shuruaat ke liye woh tarikh chunein jiska total {lucky} mein aata ho.",
  "Roz raat ko din ke 3 achhe kaam likhein — Conductor {conductor} ki urja mazboot hoti hai.",
  "Sone ka sirhaana {dir2} ki taraf rakhein.",
  "Har mahine ki {day} tarikh ko apna review din banayein.",
  "Ghar ke mukhya darwaze par {lc1} rang ka chhota shubh chinh lagayein.",
  "Kaam ki table par ek paani ka glass aur ek chhota paudha rakhein — Rahu shaant rehta hai.",
  "Har Ravivaar 20 minute dhoop mein bina phone ke bethein.",
  "Purse ya wallet mein {luckyFirst} ka chhota note/coin rakhein.",
  "Mahine mein ek din maun rakhein — bolne ki urja bachti hai.",
  "Roz raat sone se pehle 5 minute apni saans ginein — mann ki chanchalta ghatti hai.",
  "Ghar ka ek kona rozana saaf karein — 40 din mein rukavat khud kam hoti hai.",
  "Kisi bhi bade payment se pehle 24 ghante rukein.",
  "Hafte mein ek din kisi zarooratmand ko bhojan karayein.",
  "Apne mobile ke wallpaper par {lc2} rang rakhein.",
  "Purane toote saaman aur band ghadiyan ghar se nikaal dein.",
  "Roz 10 minute paidal chalein — {kp} ki urja balance hoti hai.",
  "Kagaz par apne 3 lakshya likh kar aisi jagah lagayein jo roz dikhe.",
  "Bade faisle se pehle apne mentor ya bade se ek baar poochhein.",
  "Ghar mein taaza phool rakhein — Shukra prasann rehta hai.",
  "Roz apne mata-pita ya bade ke pair chhukar aashirwad lein.",
  "Ek diary rakhein jisme sirf achhe anubhav likhein.",
  "Pani hamesha baith kar aur dheere piyein — pitta aur gussa dono kam.",
  "Har mahine income ka ek chhota hissa daan mein dein.",
  "Apni signature hamesha ek jaisi rakhein, neeche seedhi line kheenchein.",
  "Subah uthkar sabse pehle apne haath dekhein aur ek achha sankalp lein.",
  "Kaam ki shuruaat se pehle table 2 minute saaf karein.",
  "Raat ko phone bed se door rakhein — neend theek hone par faisle bhi theek hote hain.",
  "Hafte mein ek baar likh kar apna kharcha review karein.",
  "Ghar ke uttar-purv kone ko halka, khaali aur roshan rakhein.",
  "Kisi ek vidya (bhasha, skill, kala) ka roz 20 minute abhyas karein.",
  "Naya kaam shuru karne se pehle apne isht ko diya jalayein.",
];

const P = (title: string, bank: string[]): ReportPage => ({ title, bank });

export const report: Record<PageKey, ReportPage> = {
  sutra: P("Aapka Jeevan Sutra — Driver {driver} + Conductor {conductor}", [
    "Aapka jeevan ek line mein: mehnat aur samajh ka mel, jo samay ke saath bada roop leta hai.",
    "Aapka jeevan ek line mein: sangharsh se shuruaat, sthirta par khatm.",
    "Aapka jeevan ek line mein: apni shartein khud banane wali yatra.",
    "Driver aapki neev hai aur Conductor aapki chhat — dono milkar aapka ghar banate hain.",
    "Aapki kismat ek hi jhatke mein nahi khulti, parat-dar-parat khulti hai.",
    "Jab aap apni line par hote hain to samay khud raasta deta hai.",
    "Aapke jeevan ke bade mod hamesha kisi vyakti ke zariye aate hain.",
    "Aapke faisle jab likhit hote hain, tab result do guna hota hai.",
    "Aapki sabse badi jeet dheeraj se aati hai, speed se nahi.",
    "Aapke jeevan mein ek phase aisa aata hai jahan sab kuch dobara set karna padta hai — woh phase aapko banata hai.",
    "Aapke ank batate hain ki aap copy karke nahi, apna raasta banakar aage badhte hain.",
    "Jo kaam aap dil se karte hain, usme paisa apne aap peeche aata hai.",
    "Aapke jeevan mein guru ya margdarshak ka role bahut bada hai.",
    "Aap jitna apne routine ko pakka karenge, kismat utni saaf chalegi.",
    "Aapke andar ek achha shrota chhupa hai — use jagaana faydemand hai.",
    "Aapke jeevan ka sabse strong hissa 30 ke baad khulta hai.",
    "Aapka naam aapse pehle pahunchta hai — usi ko sambhalna aapki zimmedari hai.",
    "Aap jab shaant hote hain tab sabse sahi faisla lete hain.",
    "Har 9 saal mein aapka ek chapter poora hota hai aur naya shuru hota hai.",
    "Aapko chhoti-chhoti jeet celebrate karni chahiye — energy bani rehti hai.",
  ]),

  personality: P("Vyaktitva ki Gehri Tasveer", [
    "Pehli mulaqat mein log aapko shaant aur bharose-mand paate hain.",
    "Pehli mulaqat mein log aapko confident aur seedhi baat karne wala samajhte hain.",
    "Pehli mulaqat mein log aapko sochne-samajhne wala vyakti maante hain.",
    "Aap logon ko jaldi maaf kar dete hain par bhoolte nahi.",
    "Aapko apni jagah aur apna samay dono chahiye hote hain.",
    "Bade group se zyada chhote bharose-mand circle mein aap khilte hain.",
    "Tareef se zyada bharosa aapko motivate karta hai.",
    "Aap galti maan lete hain, par tab jab saamne wala izzat se kahe.",
    "Aapki chuppi ko log gussa samajh lete hain — asal mein woh sochne ka samay hota hai.",
    "Aap dikhawe se door rehte hain par quality ki pehchaan rakhte hain.",
    "Kisi ke saath ek baar bharosa toota to wapas jodna mushkil hota hai.",
    "Aap emotional to hain, par faisla dimaag se lete hain.",
    "Naye logon se milne mein thoda samay lagta hai, par jud jaayein to lambe samay tak nibhate hain.",
    "Aap kaam ko adhura chhodna pasand nahi karte.",
    "Aapke andar ek teacher hai — samjhana aapko achha lagta hai.",
    "Aap risk lete hain par calculate karke.",
    "Bhid mein bhi aap apna alag rasta chun lete hain.",
    "Aapko sunne wala chahiye — bina judge kiye sunne wala.",
    "Aapki body language aapki soch se pehle bol deti hai.",
    "Aap din ki shuruaat achhi ho to poora din sambhal lete hain.",
  ]),

  driverConductor: P("Driver {driver} aur Conductor {conductor} — Vistaar se", [
    "Driver aapki daily aadat banata hai, Conductor aapka lamba result.",
    "Jab dono ek disha mein chalte hain, kaam aadhe samay mein hota hai.",
    "Andar ka Driver jaldi bore hota hai, Conductor use rok kar rakhta hai.",
    "Aapke bade faisle Conductor ki energy par chalte hain — isliye unhe jaldi mat lein.",
    "Roz ke chhote faisle Driver ke hisaab se lein, unme aap sabse tez hain.",
    "Driver ki kamzori Conductor ki taakat se dhak jaati hai — dono ko samajhna zaroori hai.",
    "Aapki personality ka 60% Driver aur 40% Conductor dikhta hai.",
    "Naye kaam mein Driver aage rehta hai, sambhalne mein Conductor.",
    "Team ke saath kaam karte samay Conductor wali quality dikhayein.",
    "Akele kaam karte samay Driver wali quality kaam aati hai.",
    "Dono ke beech ka takraav hi aapki sabse badi seekh hai.",
    "Driver aur Conductor dono ke lucky rang mila kar pehnein — balance banta hai.",
    "Aapke naam ka ank in dono ke saath milkar aapki asli vibration banata hai.",
    "Jab thak jaayein to Conductor wale kaam karein — aaram mile ga.",
    "Driver ki jaldbaazi aur Conductor ka dheeraj — dono ke beech ka rasta chunein.",
    "Aapki growth tab tez hoti hai jab aap dono energies ko alag-alag kaam dete hain.",
    "Interview aur presentation mein Conductor wali energy dikhti hai.",
    "Ghar mein Driver wali energy zyada saamne aati hai.",
  ]),

  kua: P("Kua {kuaEff} — Disha, Vastu aur Urja", [
    "Padhai aur planning ke liye {dir2} disha behtar rahegi.",
    "Paisa, locker ya tijori {dir3} disha mein rakhein.",
    "Ghar ka mukhya darwaza saaf aur roshan rakhein.",
    "Bedroom mein aaina bed ke saamne na ho.",
    "Uttar-purv kona halka aur khaali rakhein.",
    "Toota hua saaman ghar mein na rakhein — energy rukti hai.",
    "Kaam ki table par paani ka glass aur ek paudha rakhein.",
    "Ghar ka centre khaali aur saaf rakhein.",
    "Rasoi aur bathroom aamne-saamne ho to beech mein parda rakhein.",
    "Bed ke neeche saaman bharna neend kharab karta hai.",
    "Ghar mein ek jagah aisi rakhein jahan bilkul shanti ho.",
    "Office ki kursi ke peeche deewar honi chahiye, khidki nahi.",
    "Ghar ki entry par shoe rack rakhein, khule joote nahi.",
    "Purane bill aur kagaz mahine mein ek baar hataayein.",
    "Ghar mein natural roshni jitni zyada ho utni achhi.",
    "Deewaron par udaas ya toote chitra na lagayein.",
    "Paani ka rakha bartan roz badlein.",
    "Ghar ke pooja sthal ko uttar-purv mein rakhein.",
    "Study table deewar se sata kar na rakhein, thodi jagah chhodein.",
  ]),

  luckyNumbers: P("Lucky Numbers aur Shubh Tarikhein", [
    "Bade kaam ke liye woh tarikh chunein jiska total aapke lucky number mein aata ho.",
    "Vehicle aur property ke number bhi lucky total par rakhein.",
    "Bank account aur locker number bhi check karke chunein.",
    "Nayi shuruaat ke liye lucky tarikh + lucky rang dono milayein.",
    "Bad number wali tarikh par sign karne se bachein.",
    "Agreement aur registry ki tarikh soch samajh kar chunein.",
    "Interview aur exam ke liye lucky tarikh maangna hamesha sambhav nahi — us din lucky rang pehnein.",
    "Shaadi ya sagai ki tarikh dono partner ke lucky set se milayein.",
    "Nayi dukaan ya office ka udghatan lucky tarikh par karein.",
    "Loan ki EMI date lucky number par set karein.",
    "Bade travel ki tarikh bhi lucky total par rakhein.",
    "Ghar ka number bad set mein ho to naam-plate par ek chhota shubh chinh jodein.",
    "Business ka GST/registration number badal nahi sakte — isliye naam lucky rakhein.",
    "Har mahine ki lucky tarikhein calendar par pehle se mark karein.",
    "Lucky number ka matlab jaadu nahi — sahi samay par sahi kadam hai.",
    "Do lucky numbers ka jod bhi aksar lucky nikalta hai.",
    "Bad number wale din chhoti planning aur review ka kaam karein.",
    "Paisa lene-dene ki tarikh lucky rakhein, jhagda kam hoga.",
  ]),

  colors: P("Lucky Colours aur Bad Colours", [
    "Important meeting ke din lucky colour pehnein.",
    "Ghar ki deewaron mein lucky colour ka halka shade rakhein.",
    "Bad colour ki badi cheez (curtain, car, bedsheet) se bachein.",
    "Accessory ya rumal mein lucky colour rakhna bhi kaam karta hai.",
    "Rang ka asar 40 din ke istemaal ke baad saaf dikhta hai.",
    "Poore kapde ek hi bad colour ke na pehnein.",
    "Bag, diary aur phone cover mein lucky colour chunein.",
    "Bacchon ke study room mein halka aur shaant rang rakhein.",
    "Bedroom mein tez rang neend kharab karta hai.",
    "Office desk par lucky colour ka ek chhota item rakhein.",
    "Shaadi ya bade function mein lucky colour ka dupatta/tie chalega.",
    "Gaadi ka rang lucky set se chunein to safar aasan lagta hai.",
    "Bad colour ko poori tarah band karna zaroori nahi — bas hissa chhota rakhein.",
    "Rang ke saath khushboo bhi mood banati hai — halki khushboo chunein.",
    "Interview ke din safed ya lucky colour ki shirt safe rehti hai.",
    "Rang ka asar sabse zyada tab hota hai jab woh aapki nazar mein rehta hai.",
  ]),

  strengths: P("Strengths — Vistaar se", [
    "Aapki sabse badi taakat mushkil samay mein shaant rehna hai.",
    "Aap logon ko padh lete hain — yeh business mein bada hathiyaar hai.",
    "Aap seekhne ke liye hamesha tayyar rehte hain.",
    "Aapke paas kaam ko poora karne ka dum hai.",
    "Aap apne logon ke liye khade ho jaate hain.",
    "Aapki soch practical hai, hawa-hawai nahi.",
    "Aap galti se seekh lete hain, dohrate nahi.",
    "Aap paise ki keemat samajhte hain.",
    "Aapke andar ek natural leader hai jo zaroorat par jaag jata hai.",
    "Aap detail pakad lete hain jo dusre chhod dete hain.",
    "Aap dabaav mein bhi apna kaam nahi rokte.",
    "Aap logon ko motivate kar dete hain bina jataye.",
    "Aapki memory kaam ki cheezon ke liye bahut achhi hai.",
    "Aap naye mahaul mein jaldi set ho jate hain.",
    "Aap zaroorat padne par akele bhi lad sakte hain.",
    "Aap vaada nibhate hain — yahi aapki asli izzat hai.",
  ]),

  weaknesses: P("Weaknesses — Vistaar se", [
    "Sudhaar ka tarika: har kamzori ke liye ek chhota daily rule banayein aur 40 din nibhayein.",
    "Aap zaroorat se zyada soch lete hain, jisse faisla late hota hai.",
    "Aap 'na' kehne mein hichkichate hain — yahi sabse bada nuksaan hai.",
    "Aap thakan ko ignore karte hain, phir ek saath giravat aati hai.",
    "Aap logon se ummeed zyada rakh lete hain.",
    "Aap apni tareef sun nahi paate, isliye apna kaam chhupa lete hain.",
    "Aap paison ki baat khul kar nahi karte, isliye nuksaan hota hai.",
    "Gussa aane par aap kuch der ke liye rishta kaat dete hain.",
    "Aap kaam apne haath mein rakhte hain, delegate nahi karte.",
    "Aap purani baat lambe samay tak yaad rakhte hain.",
    "Aap plan to banate hain par likhte nahi — isliye chhoot jata hai.",
    "Aap tulna karke apni khushi kam kar lete hain.",
    "Aapko aaram lena guilt jaisa lagta hai.",
    "Aap kabhi-kabhi sahi logon par bhi shak kar lete hain.",
    "Aap chhoti cheezon par zyada waqt de dete hain.",
  ]),

  childhood: P("Bachpan aur Neev (0–18 saal)", [
    "Bachpan mein aap thode sharmile par observant rahe honge.",
    "Bachpan mein aap chanchal aur sawaal poochhne wale rahe honge.",
    "Bachpan mein aap zimmedar aur samajhdar rahe honge.",
    "Padhai mein ruchi tab badhti hai jab vishay practical ho.",
    "Kisi bade (pita, guru ya rishtedar) ka asar aapke faislon par gehra pada.",
    "12–18 ke beech ek ghatna ne aapki soch hamesha ke liye badal di.",
    "Dost kam par gehre rahe.",
    "Paisa ki keemat aapne bahut jaldi samajh li.",
    "Yehi neev aage jaakar aapki sabse badi taakat banti hai.",
    "Ghar mein sunne ki jagah kam mili, isliye aap khud se baat karna seekh gaye.",
    "Khel ya kala mein aapki pratibha thi jo poori tarah nikhri nahi.",
    "School badalne ya jagah badalne ka asar aap par pada.",
    "Aapne bade hone se pehle hi zimmedari uthana seekh liya.",
    "Kisi teacher ki ek baat aaj bhi aapke saath chalti hai.",
    "Bachpan ki ek kami aaj aapki mehnat ki wajah bani hui hai.",
    "Aapko bachpan mein hi samajh aa gaya tha ki bharosa sabhi par nahi hota.",
  ]),

  youth: P("Yuva Avastha (18–30 saal)", [
    "Career ki disha is daur mein 2–3 baar badalti hai — yeh normal hai.",
    "Paisa aata hai par tikta nahi — savings ki aadat 27 ke baad banti hai.",
    "Dosti aur rishton mein ek bada dhokha ya bada sahara milta hai.",
    "26–29 ka samay turning point hai — is samay liya faisla lamba chalega.",
    "Skill par kharch kiya gaya paisa is daur ka best investment hai.",
    "Ek bada shehar ya nayi jagah aapki soch kholti hai.",
    "Is daur mein banaya network 40 ke baad kaam aata hai.",
    "Ek naukri ya kaam aisa hoga jo pasand nahi aayega par bahut sikhayega.",
    "Parivaar ki ummeedein is daur mein sabse zyada dabaav deti hain.",
    "Pehli badi kamai ka ek hissa parivaar par kharch hota hai.",
    "Is daur mein health ko halke mein lena baad mein bhaari padta hai.",
    "Ek rishta aisa banta hai jo aapki disha badal deta hai.",
    "Apni pehchaan banane ki jaldi is daur ki sabse badi galti hoti hai.",
    "Jo aadat is daur mein banegi, woh 40 tak chalegi.",
    "Ek chhoti si haar aapko asli mehnat sikha deti hai.",
  ]),

  midLife: P("Madhya Jeevan (30–45 saal)", [
    "Yeh aapki kamai aur pehchaan ka sabse strong daur hai.",
    "Property, vehicle ya apna setup is daur mein banta hai.",
    "Parivaar ki zimmedari badhti hai — time management sabse badi challenge.",
    "Health ko ignore karna is daur ki sabse badi galti hoti hai.",
    "Naye log aapke naam se judte hain — network hi aapki taakat hai.",
    "Ek purana rishta wapas judta hai aur fayda deta hai.",
    "Income ke do zariye banane ka sahi samay yahi hai.",
    "36–42 ke beech ek badi safalta ka yog banta hai.",
    "Is daur mein liya gaya loan soch samajh kar lein.",
    "Bacchon ya juniors ki zimmedari aapko aur mazboot banati hai.",
    "Ek badi seekh: sab kuch khud karne se team banana behtar hai.",
    "Naam kamane ke saath dushman bhi bante hain — shaant rahein.",
    "Is daur mein kiya gaya nivesh 50 ke baad sahara banta hai.",
    "Aapki salah ki demand badhne lagti hai.",
    "Purane dost chhoot jate hain, naye professional rishte bante hain.",
  ]),

  maturity: P("Paripakvta aur Uttar Jeevan (45+ saal)", [
    "Ab kaam se zyada naam matter karta hai.",
    "Guidance dene ka role milta hai — log salah lene aate hain.",
    "Aay ke ek se zyada zariye ban jate hain.",
    "Sehat par kharcha aur dhyan dono badhta hai.",
    "Bachchon/junior team ki taraki aapki khushi ban jaati hai.",
    "Daan aur seva se rukavatein khud khulti hain.",
    "60 ke baad shanti aur santosh ka daur — bhaag-daud khatm.",
    "Adhyatm ki taraf jhukav badhta hai.",
    "Anubhav baantne ka mauka milta hai — likhna ya sikhana suit karega.",
    "Ek lambi yatra ya teerth ka yog banta hai.",
    "Jo naam aapne banaya woh aage tak chalta hai.",
    "Property ya paisa baantne ka faisla soch kar aur likh kar karein.",
    "Purane rishte dobara zinda karne ka samay hai.",
    "Rozana routine hi is daur mein sabse badi dawai hai.",
    "Ek shauk (hobby) dobara shuru karna aapko jawan rakhega.",
  ]),

  career: P("Career Path — Job aur Business dono", [
    "Interview ya joining ke liye lucky numbers ki tarikh chunein.",
    "Job change ka best samay personal year 1, 5 ya 8 hota hai.",
    "Partnership tab hi karein jab likhit agreement ho.",
    "Pehle 3 saal mein munafa kam, seekh zyada milegi.",
    "Cash flow ka hisaab roz likhein.",
    "Team mein aapke bad numbers wale log conflict la sakte hain — balance rakhein.",
    "Ek skill aisi banayein jiske liye log aapko dhoondhein.",
    "Apna kaam online dikhana aapke liye zaroori hai.",
    "Boss ya senior se rishta seedha aur likhit rakhein.",
    "Salary se zyada seekh dene wali job chunein — 3 saal mein farq dikhega.",
    "Business shuru karne se pehle 6 mahine ka kharcha bacha kar rakhein.",
    "Ek hi kaam ke do customer segment rakhein — risk ghat jata hai.",
    "Apne kaam ka record aur portfolio banate rahein.",
    "Kaam mein shortcut aapke liye mehnga padta hai.",
    "Career ka bada faisla akele nahi, mentor se poochh kar lein.",
    "Naukri chhodne se pehle agla raasta pakka karein.",
  ]),

  money: P("Dhan, Nivesh aur Kharcha", [
    "Income ka 20% automatic bachat mein daalein.",
    "Loan sirf income-generating asset ke liye lein.",
    "Property aur gold aapke liye safe long-term rahenge.",
    "Speculative trading se door rahein jab tak seekh na jaayein.",
    "Har mahine ka budget 50-30-20 rule par banayein.",
    "Emergency fund 6 mahine ke kharche ka rakhein.",
    "Insurance ko investment na samjhein.",
    "Kisi ko udhaar dene se pehle likhit rakhein.",
    "Do bank account rakhein — ek kharche ka, ek bachat ka.",
    "Har saal ek baar apna poora hisaab likh kar dekhein.",
    "Credit card ka bill poora bharein, minimum nahi.",
    "Nivesh ko har mahine automatic karein, mood par mat chhodein.",
    "Bade kharche se pehle 24 ghante rukna aapke liye jaruri niyam hai.",
    "Paise ki baat parivaar mein khul kar karein.",
    "Ek nivesh aisa rakhein jise haath lagana mushkil ho.",
    "Sona/chandi lene ka samay lucky tarikh par rakhein.",
  ]),

  love: P("Prem, Vivah aur Rishte", [
    "Shaadi ke liye shubh samay personal year 2 aur 6 hai.",
    "Rishta chalane ka sutra: roz 15 minute bina phone ki baat.",
    "Purane jhagde dobara na uthayein.",
    "Partner ki taarif public mein karein, shikayat akele mein.",
    "Aapko sunne wala partner chahiye, sirf salah dene wala nahi.",
    "Rishton mein aapki chuppi sabse bada misunderstanding banati hai.",
    "Chhote tohfe aapke rishte mein bade kaam karte hain.",
    "Ek hafte mein ek baar sirf dono ka waqt rakhein.",
    "Rishton mein hisaab-kitab rakhna doori badhata hai.",
    "Partner ke parivaar se rishta banane mein pehal aapko karni hogi.",
    "Gussa aane par 10 minute ke liye kamre se bahar jaayein.",
    "Maafi maangna aapki haar nahi, rishte ki jeet hai.",
    "Bachpan ki kami rishte mein ummeed banakar dikhti hai — use pehchanein.",
    "Rishte mein sach bolna kadwa lagta hai par bachata hai.",
    "Ek doosre ke lucky rang ka dhyan rakhein — chhoti cheez, bada asar.",
  ]),

  family: P("Parivaar aur Santaan", [
    "Parivaar aapki sabse badi urja ka source hai.",
    "Maa-pita ki sehat par 40 ke baad dhyan dena hoga.",
    "Bachchon ke saath dosti wala rishta zyada kaam karega.",
    "Ghar ke bade faisle lucky tarikh par lein.",
    "Ghar ka mandir/positive corner uttar-purv mein rakhein.",
    "Parivaar mein aapki baat suni jaati hai — narmi se rakhein.",
    "Bachchon ki padhai ki disha unke apne mulank se chunein.",
    "Saal mein ek family trip rishton ko sambhal deti hai.",
    "Ghar mein sabke saath ek time ka khana zaroori hai.",
    "Bhai-behan se paisa ka lena-dena likhit rakhein.",
    "Bacchon ke saamne partner se behas na karein.",
    "Ghar ke buzurgon ka aashirwad aapke kaam ki speed badhata hai.",
    "Ghar ki ek zimmedari har sadasya ko dein.",
    "Parivaar ke liye kiya gaya kharcha kabhi nuksaan nahi hota.",
    "Ghar mein hafte mein ek baar sabki baat sunne ka samay rakhein.",
  ]),

  health: P("Swasthya aur Urja", [
    "Roz 30 minute walk ya yoga aapki sabse sasti dawai hai.",
    "Paani aur khana time par — irregular timing hi sabse badi problem banti hai.",
    "Saal mein ek baar full body checkup zaroori hai.",
    "Neend 7 ghante se kam hui to mood aur faisle dono bigadte hain.",
    "Screen time raat mein kam karein.",
    "Chai/coffee din mein do se zyada nahi.",
    "Kamar aur gardan ke liye har ghante 2 minute stretch.",
    "Saans ka abhyas (pranayam) aapke liye sabse strong upay hai.",
    "Bahar ka khana hafte mein ek baar se zyada nahi.",
    "Dhoop roz 15 minute lena zaroori hai.",
    "Dawa se zyada routine par bharosa karein.",
    "Mann ki thakan ko bhi bimari maanein aur aaram dein.",
    "Vajan har mahine ek baar check karein.",
    "Khud ke liye hafte mein ek din bina kaam ka rakhein.",
    "Chot ya dard ko taalna aapke liye mehnga padta hai.",
  ]),

  education: P("Shiksha aur Skills", [
    "Practical skills theory se zyada fayda denge.",
    "Online certification aapki value badha dega.",
    "Ek subject mein mahir banna — 5 mein average se behtar hai.",
    "Roz 45 minute deep-focus study slot rakhein.",
    "Notes apne shabdon mein likhein.",
    "Har 3 mahine mein ek naya chhota course poora karein.",
    "Jo seekha use kisi ko sikhayein — pakka yaad rahega.",
    "Padhai ka time subah rakhein to yaad zyada rehta hai.",
    "Ek saal mein ek badi kitab poori zaroor padhein.",
    "Group study aapke liye tabhi kaam karti hai jab log serious hon.",
    "Skill ka proof banayein — certificate, project ya portfolio.",
    "Bhasha ki skill aapke career ko seedha upar le jaayegi.",
    "Padhai ke beech 5 minute ka break memory badhata hai.",
    "Mobile door rakh kar padhna aapke liye zaroori hai.",
  ]),

  chart: P("Birth Chart — Missing, Repeated aur Upay", [
    "Upay 40 din lagatar karein tabhi asar dikhega.",
    "Missing ank ka matlab kismat kharab nahi — us kshetra mein mehnat zyada.",
    "Repeated ank ka matlab us energy ka over-use — use sahi jagah lagayein.",
    "Chart har roz nahi badalta, par aapki aadatein use sambhal sakti hain.",
    "Missing ank ke liye us ank se judi cheez ka daan sabse aasan upay hai.",
    "Chart ka khaali khaana bharne ke liye us ank ke kaam roz karein.",
    "Chart mein jo ank zyada hai, uske gun aap dusron ko sikha sakte hain.",
    "Upay tab kaam karta hai jab neeyat saaf ho.",
    "Chart ko dekh kar darne ki zarurat nahi — yeh sirf map hai.",
    "Missing ank ke saal-dar-saal asar alag hote hain, isliye review karte rahein.",
    "Ghar ke doosre logon ka chart bhi banwa kar milaan karein.",
    "Grid ka har khaana ek jeevan-kshetra hai, sirf number nahi.",
  ]),

  planes: P("Planes ka Vistaar", [
    "Plane matlab grid ki woh line (row, column ya diagonal) jisme teeno ank maujood hon.",
    "Adhura plane bhi kaam karta hai, bas mehnat zyada maangta hai.",
    "Plane ka fayda tabhi milta hai jab uski energy ka istemal ho.",
    "Do plane active hon to unka mel aapki khaas pehchaan banata hai.",
    "Plane ke ank ka rang aur disha bhi us plane ko mazboot karti hai.",
    "Mental plane strong ho to planning ka kaam chunein.",
    "Emotional plane strong ho to logon se juda kaam chunein.",
    "Practical plane strong ho to execution wala kaam chunein.",
    "Plane adhura ho to us ank ka upay 40 din chalayein.",
  ]),

  yogas: P("Yogas aur Chart ke Sanket", [
    "Chart ke sanket sirf disha dete hain, mehnat aapki hi kaam aati hai.",
    "Yoga ka matlab guarantee nahi, extra support hai.",
    "Yoga na hone par bhi mehnat se wahi result banaya ja sakta hai.",
    "Golden yoga wale logon ko naam jaldi milta hai, par sambhalna padta hai.",
    "Silver yoga wale logon ko paisa dheere par pakka milta hai.",
    "Yoga ke saath sahi rang aur disha use karne se asar badhta hai.",
    "Chart mein 5 ka hona har yoga ko jodne ka kaam karta hai.",
    "Ek yoga adhura ho to uske missing ank par kaam karein.",
  ]),

  nameNum: P("Naam Numerology (Chaldean)", [
    "Signature hamesha ek jaisi rakhein — vibration sthir hoti hai.",
    "Naam ke neeche seedhi line kheenchna support badhata hai.",
    "Business ka naam bhi apne lucky number par rakhein.",
    "Naam badalne se pehle 3 mahine trial karein.",
    "Nickname bhi vibration banata hai — soch samajh kar chunein.",
    "Email ID aur social handle bhi naam ki tarah kaam karte hain.",
    "Naam ki spelling har jagah ek jaisi rakhein.",
    "Naam ke saath surname ka mel bhi dekha jata hai.",
    "Bacchon ka naam rakhte samay unka mulank dekhein.",
    "Naam ka ank aapke pehchaan ka rang decide karta hai.",
  ]),

  mobileNum: P("Mobile Number ki Vibration", [
    "Business aur personal number alag rakhein.",
    "Naya number lete samay total lucky number par rakhein.",
    "Number mein 0 zyada ho to uske aas-paas ke ank par dhyan dein.",
    "Ek hi number 10 saal se zyada chalana bhi asar banata hai.",
    "Number ka pehla hissa aapki shuruaat, aakhri hissa result dikhata hai.",
    "Number badalne se pehle 40 din naya number parallel chalayein.",
    "Payment aur bank se juda number lucky rakhein.",
    "WhatsApp business number alag rakhna faydemand hai.",
  ]),

  mobilePairs: P("Mobile Number — Pair-by-Pair Asar", [
    "Har do lagataar ank ka jodha ek chhoti energy banata hai — poora number inhi jodon ka jod hai.",
    "Ek-do shatru jode se ghabrayein nahi, total zyada matter karta hai.",
    "Shatru jode zyada hon to number ka istemal kam karein.",
    "Jodon ka asar call aur payment dono par dikhta hai.",
    "Number ke aakhri do ank sabse zyada asar dete hain.",
  ]),

  remedies: P("Vishesh Upay aur Daily Routine", [
    "Kisi bhi upay ko kam se kam 40 din lagatar karein — beech mein toota to phir se shuru karein.",
    "Upay ke saath mehnat zaroori hai — upay raasta saaf karta hai, chalna aapko hai.",
    "Ek samay mein 3 se zyada upay na karein.",
    "Upay ka asar diary mein likh kar dekhein.",
    "Daan hamesha bina jataye karein.",
    "Subah ka pehla ghanta aur raat ka aakhri ghanta sabse asar-daar hota hai.",
    "Upay parivaar ke saath karein to asar do guna hota hai.",
  ]),

  year: P("Personal Year {year} — Mahina-wise Analysis", [
    "Har mahine ka number us mahine ka mood batata hai.",
    "Saal ka bada kaam strong mahine mein rakhein.",
    "Kamzor mahine mein planning aur review karein.",
    "Personal year saal ki shuruaat mein nahi, aapke janmdin se badalta hai.",
    "Is saal ke faisle agle saal ka base banate hain.",
    "Har mahine ke pehle hafte mein us mahine ka plan likh lein.",
  ]),
};
