/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as CalculatorRouteImport } from './routes/calculator'
import { Route as ConsultationRouteImport } from './routes/consultation'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as GenerateRouteImport } from './routes/generate'
import { Route as MeRouteImport } from './routes/me'
import { Route as PayRouteImport } from './routes/pay'
import { Route as ReportRouteImport } from './routes/report'
import { Route as ServicesRouteImport } from './routes/services'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as AdminIndexRouteImport } from './routes/admin/index'
import { Route as AdminAuthRouteImport } from './routes/admin/auth'
import { Route as ServicesAstrologyRouteImport } from './routes/services.astrology'
import { Route as ServicesJyotishRouteImport } from './routes/services.jyotish'
import { Route as ServicesNumerologyRouteImport } from './routes/services.numerology'
import { Route as SubadminIndexRouteImport } from './routes/subadmin/index'
import { Route as SubadminAuthRouteImport } from './routes/subadmin/auth'
import { Route as SuperadminIndexRouteImport } from './routes/superadmin/index'
import { Route as SuperadminLoginRouteImport } from './routes/superadmin/login'
import { Route as SuperadminSubmissionsRouteImport } from './routes/superadmin/submissions'
import { Route as ApiPublicGeoRouteImport } from './routes/api/public/geo'
import { Route as ApiPublicTelegramSubRouteImport } from './routes/api/public/telegram/$sub'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const CalculatorRoute = CalculatorRouteImport.update({
  id: '/calculator',
  path: '/calculator',
  getParentRoute: () => rootRouteImport,
} as any)
const ConsultationRoute = ConsultationRouteImport.update({
  id: '/consultation',
  path: '/consultation',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const GenerateRoute = GenerateRouteImport.update({
  id: '/generate',
  path: '/generate',
  getParentRoute: () => rootRouteImport,
} as any)
const MeRoute = MeRouteImport.update({
  id: '/me',
  path: '/me',
  getParentRoute: () => rootRouteImport,
} as any)
const PayRoute = PayRouteImport.update({
  id: '/pay',
  path: '/pay',
  getParentRoute: () => rootRouteImport,
} as any)
const ReportRoute = ReportRouteImport.update({
  id: '/report',
  path: '/report',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesRoute = ServicesRouteImport.update({
  id: '/services',
  path: '/services',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/admin/',
  path: '/admin/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminAuthRoute = AdminAuthRouteImport.update({
  id: '/admin/auth',
  path: '/admin/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesAstrologyRoute = ServicesAstrologyRouteImport.update({
  id: '/astrology',
  path: '/astrology',
  getParentRoute: () => ServicesRoute,
} as any)
const ServicesJyotishRoute = ServicesJyotishRouteImport.update({
  id: '/jyotish',
  path: '/jyotish',
  getParentRoute: () => ServicesRoute,
} as any)
const ServicesNumerologyRoute = ServicesNumerologyRouteImport.update({
  id: '/numerology',
  path: '/numerology',
  getParentRoute: () => ServicesRoute,
} as any)
const SubadminIndexRoute = SubadminIndexRouteImport.update({
  id: '/subadmin/',
  path: '/subadmin/',
  getParentRoute: () => rootRouteImport,
} as any)
const SubadminAuthRoute = SubadminAuthRouteImport.update({
  id: '/subadmin/auth',
  path: '/subadmin/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const SuperadminIndexRoute = SuperadminIndexRouteImport.update({
  id: '/superadmin/',
  path: '/superadmin/',
  getParentRoute: () => rootRouteImport,
} as any)
const SuperadminLoginRoute = SuperadminLoginRouteImport.update({
  id: '/superadmin/login',
  path: '/superadmin/login',
  getParentRoute: () => rootRouteImport,
} as any)
const SuperadminSubmissionsRoute = SuperadminSubmissionsRouteImport.update({
  id: '/superadmin/submissions',
  path: '/superadmin/submissions',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicGeoRoute = ApiPublicGeoRouteImport.update({
  id: '/api/public/geo',
  path: '/api/public/geo',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicTelegramSubRoute = ApiPublicTelegramSubRouteImport.update({
  id: '/api/public/telegram/$sub',
  path: '/api/public/telegram/$sub',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/calculator': typeof CalculatorRoute
  '/consultation': typeof ConsultationRoute
  '/contact': typeof ContactRoute
  '/generate': typeof GenerateRoute
  '/me': typeof MeRoute
  '/pay': typeof PayRoute
  '/report': typeof ReportRoute
  '/services': typeof ServicesRouteWithChildren
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/admin/auth': typeof AdminAuthRoute
  '/services/astrology': typeof ServicesAstrologyRoute
  '/services/jyotish': typeof ServicesJyotishRoute
  '/services/numerology': typeof ServicesNumerologyRoute
  '/subadmin/auth': typeof SubadminAuthRoute
  '/superadmin/login': typeof SuperadminLoginRoute
  '/superadmin/submissions': typeof SuperadminSubmissionsRoute
  '/admin/': typeof AdminIndexRoute
  '/subadmin/': typeof SubadminIndexRoute
  '/superadmin/': typeof SuperadminIndexRoute
  '/api/public/geo': typeof ApiPublicGeoRoute
  '/api/public/telegram/$sub': typeof ApiPublicTelegramSubRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/calculator': typeof CalculatorRoute
  '/consultation': typeof ConsultationRoute
  '/contact': typeof ContactRoute
  '/generate': typeof GenerateRoute
  '/me': typeof MeRoute
  '/pay': typeof PayRoute
  '/report': typeof ReportRoute
  '/services': typeof ServicesRouteWithChildren
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/admin/auth': typeof AdminAuthRoute
  '/services/astrology': typeof ServicesAstrologyRoute
  '/services/jyotish': typeof ServicesJyotishRoute
  '/services/numerology': typeof ServicesNumerologyRoute
  '/subadmin/auth': typeof SubadminAuthRoute
  '/superadmin/login': typeof SuperadminLoginRoute
  '/superadmin/submissions': typeof SuperadminSubmissionsRoute
  '/admin': typeof AdminIndexRoute
  '/subadmin': typeof SubadminIndexRoute
  '/superadmin': typeof SuperadminIndexRoute
  '/api/public/geo': typeof ApiPublicGeoRoute
  '/api/public/telegram/$sub': typeof ApiPublicTelegramSubRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/calculator': typeof CalculatorRoute
  '/consultation': typeof ConsultationRoute
  '/contact': typeof ContactRoute
  '/generate': typeof GenerateRoute
  '/me': typeof MeRoute
  '/pay': typeof PayRoute
  '/report': typeof ReportRoute
  '/services': typeof ServicesRouteWithChildren
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/admin/auth': typeof AdminAuthRoute
  '/services/astrology': typeof ServicesAstrologyRoute
  '/services/jyotish': typeof ServicesJyotishRoute
  '/services/numerology': typeof ServicesNumerologyRoute
  '/subadmin/auth': typeof SubadminAuthRoute
  '/superadmin/login': typeof SuperadminLoginRoute
  '/superadmin/submissions': typeof SuperadminSubmissionsRoute
  '/admin/': typeof AdminIndexRoute
  '/subadmin/': typeof SubadminIndexRoute
  '/superadmin/': typeof SuperadminIndexRoute
  '/api/public/geo': typeof ApiPublicGeoRoute
  '/api/public/telegram/$sub': typeof ApiPublicTelegramSubRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/calculator'
    | '/consultation'
    | '/contact'
    | '/generate'
    | '/me'
    | '/pay'
    | '/report'
    | '/services'
    | '/sitemap.xml'
    | '/admin/auth'
    | '/services/astrology'
    | '/services/jyotish'
    | '/services/numerology'
    | '/subadmin/auth'
    | '/superadmin/login'
    | '/superadmin/submissions'
    | '/admin/'
    | '/subadmin/'
    | '/superadmin/'
    | '/api/public/geo'
    | '/api/public/telegram/$sub'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/calculator'
    | '/consultation'
    | '/contact'
    | '/generate'
    | '/me'
    | '/pay'
    | '/report'
    | '/services'
    | '/sitemap.xml'
    | '/admin/auth'
    | '/services/astrology'
    | '/services/jyotish'
    | '/services/numerology'
    | '/subadmin/auth'
    | '/superadmin/login'
    | '/superadmin/submissions'
    | '/admin'
    | '/subadmin'
    | '/superadmin'
    | '/api/public/geo'
    | '/api/public/telegram/$sub'
  id:
    | '__root__'
    | '/'
    | '/auth'
    | '/calculator'
    | '/consultation'
    | '/contact'
    | '/generate'
    | '/me'
    | '/pay'
    | '/report'
    | '/services'
    | '/sitemap.xml'
    | '/admin/auth'
    | '/services/astrology'
    | '/services/jyotish'
    | '/services/numerology'
    | '/subadmin/auth'
    | '/superadmin/login'
    | '/superadmin/submissions'
    | '/admin/'
    | '/subadmin/'
    | '/superadmin/'
    | '/api/public/geo'
    | '/api/public/telegram/$sub'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthRoute: typeof AuthRoute
  CalculatorRoute: typeof CalculatorRoute
  ConsultationRoute: typeof ConsultationRoute
  ContactRoute: typeof ContactRoute
  GenerateRoute: typeof GenerateRoute
  MeRoute: typeof MeRoute
  PayRoute: typeof PayRoute
  ReportRoute: typeof ReportRoute
  ServicesRoute: typeof ServicesRouteWithChildren
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  AdminAuthRoute: typeof AdminAuthRoute
  SubadminAuthRoute: typeof SubadminAuthRoute
  SuperadminLoginRoute: typeof SuperadminLoginRoute
  SuperadminSubmissionsRoute: typeof SuperadminSubmissionsRoute
  AdminIndexRoute: typeof AdminIndexRoute
  SubadminIndexRoute: typeof SubadminIndexRoute
  SuperadminIndexRoute: typeof SuperadminIndexRoute
  ApiPublicGeoRoute: typeof ApiPublicGeoRoute
  ApiPublicTelegramSubRoute: typeof ApiPublicTelegramSubRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/calculator': {
      id: '/calculator'
      path: '/calculator'
      fullPath: '/calculator'
      preLoaderRoute: typeof CalculatorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/consultation': {
      id: '/consultation'
      path: '/consultation'
      fullPath: '/consultation'
      preLoaderRoute: typeof ConsultationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/generate': {
      id: '/generate'
      path: '/generate'
      fullPath: '/generate'
      preLoaderRoute: typeof GenerateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/me': {
      id: '/me'
      path: '/me'
      fullPath: '/me'
      preLoaderRoute: typeof MeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pay': {
      id: '/pay'
      path: '/pay'
      fullPath: '/pay'
      preLoaderRoute: typeof PayRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/report': {
      id: '/report'
      path: '/report'
      fullPath: '/report'
      preLoaderRoute: typeof ReportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services': {
      id: '/services'
      path: '/services'
      fullPath: '/services'
      preLoaderRoute: typeof ServicesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/admin'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/auth': {
      id: '/admin/auth'
      path: '/admin/auth'
      fullPath: '/admin/auth'
      preLoaderRoute: typeof AdminAuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services/astrology': {
      id: '/services/astrology'
      path: '/astrology'
      fullPath: '/services/astrology'
      preLoaderRoute: typeof ServicesAstrologyRouteImport
      parentRoute: typeof ServicesRoute
    }
    '/services/jyotish': {
      id: '/services/jyotish'
      path: '/jyotish'
      fullPath: '/services/jyotish'
      preLoaderRoute: typeof ServicesJyotishRouteImport
      parentRoute: typeof ServicesRoute
    }
    '/services/numerology': {
      id: '/services/numerology'
      path: '/numerology'
      fullPath: '/services/numerology'
      preLoaderRoute: typeof ServicesNumerologyRouteImport
      parentRoute: typeof ServicesRoute
    }
    '/subadmin/': {
      id: '/subadmin/'
      path: '/subadmin'
      fullPath: '/subadmin/'
      preLoaderRoute: typeof SubadminIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/subadmin/auth': {
      id: '/subadmin/auth'
      path: '/subadmin/auth'
      fullPath: '/subadmin/auth'
      preLoaderRoute: typeof SubadminAuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/superadmin/': {
      id: '/superadmin/'
      path: '/superadmin'
      fullPath: '/superadmin/'
      preLoaderRoute: typeof SuperadminIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/superadmin/login': {
      id: '/superadmin/login'
      path: '/superadmin/login'
      fullPath: '/superadmin/login'
      preLoaderRoute: typeof SuperadminLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/superadmin/submissions': {
      id: '/superadmin/submissions'
      path: '/superadmin/submissions'
      fullPath: '/superadmin/submissions'
      preLoaderRoute: typeof SuperadminSubmissionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/geo': {
      id: '/api/public/geo'
      path: '/api/public/geo'
      fullPath: '/api/public/geo'
      preLoaderRoute: typeof ApiPublicGeoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/telegram/$sub': {
      id: '/api/public/telegram/$sub'
      path: '/api/public/telegram/$sub'
      fullPath: '/api/public/telegram/$sub'
      preLoaderRoute: typeof ApiPublicTelegramSubRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface ServicesRouteChildren {
  ServicesAstrologyRoute: typeof ServicesAstrologyRoute
  ServicesJyotishRoute: typeof ServicesJyotishRoute
  ServicesNumerologyRoute: typeof ServicesNumerologyRoute
}

const ServicesRouteChildren: ServicesRouteChildren = {
  ServicesAstrologyRoute: ServicesAstrologyRoute,
  ServicesJyotishRoute: ServicesJyotishRoute,
  ServicesNumerologyRoute: ServicesNumerologyRoute,
}

const ServicesRouteWithChildren = ServicesRoute._addFileChildren(
  ServicesRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthRoute: AuthRoute,
  CalculatorRoute: CalculatorRoute,
  ConsultationRoute: ConsultationRoute,
  ContactRoute: ContactRoute,
  GenerateRoute: GenerateRoute,
  MeRoute: MeRoute,
  PayRoute: PayRoute,
  ReportRoute: ReportRoute,
  ServicesRoute: ServicesRouteWithChildren,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  AdminAuthRoute: AdminAuthRoute,
  SubadminAuthRoute: SubadminAuthRoute,
  SuperadminLoginRoute: SuperadminLoginRoute,
  SuperadminSubmissionsRoute: SuperadminSubmissionsRoute,
  AdminIndexRoute: AdminIndexRoute,
  SubadminIndexRoute: SubadminIndexRoute,
  SuperadminIndexRoute: SuperadminIndexRoute,
  ApiPublicGeoRoute: ApiPublicGeoRoute,
  ApiPublicTelegramSubRoute: ApiPublicTelegramSubRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
